conda.recipe/meta.yaml, conda.recipe/run_test.py
This is a simple change to the conda recipe, making use of templating to dynamically set the conda package version information based on git tags. If you set `git_tag: v5.0.0`, for example, you will get a conda package called `pymca-5.0.0-np19py27_0`. As of this commit, if `git_tag: master`, it would produce `pymca-5.0.0-np19py27_10`, indicating the 10th commit after the v5.0.0 tag.
I recommend leaving `git_tag: master` committed in the repo, and making temporary local modifications in the working directory when creating conda packages for any particular release.
=> updates conda recipe version info

PyMca5/PyMcaIO/NumpyStack.py, PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
Hi Armando,
We have a use case which requires us to operate on a numpy array instead of a file. The data is already loaded in memory. We will use the methods in this pull request to integrate PyMca with our data parallel, big data processing pipeline Savu: https://github.com/DiamondLightSource/Savu. Creating this new data "type" seemed the best way to achieve this; I'd appreciate your thoughts!
Best wishes,
Aaron
=> Adds ability to fit to numpy arrays

PyMca5/PyMcaGui/pymca/ScanWindow.py
Closes  #54 by using the SVG rendering rather than the pixmap. 
This reintroduces  a minor curve clipping bug, when the applied zoom uses a Y range that does not cover all the data range for the given X range.
=> Use the SvgRenderer if available 

PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
Hi Armando,
I am running PyMca inside some MPI as part of savu, and the file saving of the fit images, and the creation of the IMAGES folder is causing locking issues for me. Instead I will just grab the images from the output dictionary without needing to save.
I added a parameter (nosave) to McaAdvancedFitBatch in order to run off the file saving. Is this ok? Or was there a better way I missed?
Aaron
=> Adds a parameter so that we can turn off file saving

PyMca5/PyMcaIO/HDF5Stack1D.py, PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
Hi Armando,
This PR does two things:
1/ fixes a bug I introduced in the last PR.
2/ Since January, our beamlines output nexus files with multiple entries. These entries are very different, however the PyMca batch fit assumes all the entries will be the same and tries to batch over all of these entries, which fails.
I added a try-catch around this statement so it carries on. It's been tested by users and they are happy. Incidentally, now we know that the batch fit can do this, we might write something on our side to exploit it in the future.
Also, since the users who noticed this bug, also want to process their data on windows, they asked me to ask when the next windows release will be? Would it be possible to do a patch release for windows that fixes this bug?
Aaron
=> Fixes some bugs

PyMca5/PyMcaGui/io/hdf5/HDF5DatasetTable.py, PyMca5/PyMcaGui/io/hdf5/HDF5DatasetView.py, PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py, doc/source/PyMca5.PyMcaGui.io.hdf5.rst
If silx is installed, use the `DataViewFrame` widget instead of `NumpyArrayTableWidget`, to show data when user clicks on "Show information" on a HDF5 dataset.
I leave the status as work in progress, because it is possible that the `DataView` module will be moved to another package than `silx.gui.widgets` before the coming release.
=> Use silx DataView widget

PyMca5/PyMcaGui/plotting/Q4PyMcaPrintPreview.py
When an item is selected with a left click, and then we try to resize another element without an intermediate click, the first item is dragged while the new one is resized.
This commit make sure the selection is cleared prior to resizing an item.
=> Fix minor selection bug in PrintPreview

PyMca5/PyMcaIO/JcampFileParser.py, PyMca5/PyMcaIO/JcampReader.py
Use mmap instead of readline under 64-bit platforms.
=> Speed up block parsing.

PyMca5/PyMcaGui/physics/xrf/PeakIdentifier.py, PyMca5/PyMcaGui/pymca/PyMcaMain.py, PyMca5/PyMcaGui/pymca/QStackWidget.py
Closes #97 
Also fixes a typo when setting the ROI imaging window title to the source name.
=> [PeakIdentifier] fix NameError and deprecation warning

PyMca5/PyMcaCore/Plugin1DBase.py, PyMca5/PyMcaGui/PluginsToolButton.py, PyMca5/PyMcaGui/io/hdf5/Hdf5DatasetView.py, PyMca5/PyMcaGui/io/hdf5/Hdf5NodeView.py, PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py, PyMca5/PyMcaGui/pymca/PyMcaNexusWidget.py, PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py, PyMca5/PyMcaPlugins/MedianFilterScanDeglitchPlugin.py, PyMca5/PyMcaPlugins/XASSelfattenuationPlugin.py
This PR provides:
- a `PluginsToolButton` to load plugins and serve as interface between the silx plot widget and `Plugin1DBase` (from PR #49 with minor modifications)
- modification to `Plugin1DBase` to support silx plot widgets via  `PluginsToolButton`(form PR #49)
- a `DataViewerFrame` modified to provide the plugin toolbutton, used in `QNexusWidget`
It makes minor changes to the right click menu behavior in `QNexusWidget` (open a menu also for groups and string datasets).
.
=> [Hdf5DatasetView] plugins support

PyMca5/PyMcaCore/Plugin1DBase.py, PyMca5/PyMcaGui/math/PCAWindow.py, PyMca5/PyMcaGui/math/SGWindow.py, PyMca5/PyMcaGui/math/SNIPWindow.py, PyMca5/PyMcaGui/math/SimpleActions.py, PyMca5/PyMcaGui/math/fitting/RateLawWindow.py, PyMca5/PyMcaGui/physics/xas/XASNormalizationWindow.py, PyMca5/PyMcaGui/physics/xrf/MaterialEditor.py, PyMca5/PyMcaGui/plotting/MaskImageWidget.py, PyMca5/PyMcaGui/plotting/ProfileScanWidget.py, PyMca5/PyMcaGui/pymca/LegacyScanWindow.py, PyMca5/PyMcaGui/pymca/McaWindow.py, PyMca5/PyMcaGui/pymca/PyMcaMain.py, PyMca5/PyMcaGui/pymca/ScanFitToolButton.py, PyMca5/PyMcaGui/pymca/ScanWindow.py, PyMca5/PyMcaGui/pymca/ScanWindowInfoWidget.py, PyMca5/PyMcaGui/pymca/SumRulesTool.py, PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py, PyMca5/PyMcaPlugins/AlignmentScanPlugin.py, PyMca5/PyMcaPlugins/KineticsPlugin.py, PyMca5/PyMcaPlugins/MedianFilterScanDeglitchPlugin.py, PyMca5/PyMcaPlugins/StackScanWindowPlugin.py, PyMca5/PyMcaPlugins/StackShowSpectra.py, PyMca5/PyMcaPlugins/XASPlugin.py, PyMca5/PyMcaPlugins/XMCDPlugin.py, PyMca5/PyMcaPlugins/optional/JsonRpc1DPlugin.py, PyMca5/PyMcaPlugins/optional/TaurusPlugin1D.py, PyMca5/__init__.py
This PR implements a ScanWindow based on a silx PlotWindow. Most of the code comes from unmerged PR #49, but there are new updates due to recent deprecations in silx (PlotActions refactoring).
It also replaces the legacy PyMca `PlotWindow` with the silx `PlotWindow` in various plugins accessible from the `ScanWindow`.
PR #91 should be merged first (this branch is based on it, because it implements PluginsToolButton).
To do in separate pull requests:
- stop using `LegacyScanWindow` (still used in `McaWindow` & `XMCDScanWindow`)
- test and fix `XMCDWindow` (heavy use of `.dataObjectdict` for accessing curves)
- add a plugin toolbutton to all new silx  `PlotWindow` instances
=> [5.3] ScanWindow based on a silx plot

PyMca5/PyMcaGui/math/StripBackgroundWidget.py, PyMca5/PyMcaGui/math/fitting/SimpleFitGui.py, PyMca5/PyMcaGui/physics/xas/XASNormalizationWindow.py, PyMca5/PyMcaGui/physics/xas/XASWindow.py, PyMca5/PyMcaGui/physics/xrf/FitParam.py, PyMca5/PyMcaGui/physics/xrf/QXTube.py, PyMca5/PyMcaGui/plotting/ProfileScanWidget.py, PyMca5/PyMcaPhysics/xas/XASClass.py
Use a silx PlotWindow instead of a PyMca PlotWindow.
Some PlotWindow directly related to ScanWindow have already been converted in #96.
TODO in separate PRs:
- deal with `McaAdvancedFit` (more complicated than all the other widgets)
- `ImageView`: use the silx one or keep this one? Not used in PyMca but in external plugins. One notable change: signature of `__init__`
- add a `PrintPreview` toolbutton to all these `PlotWindow`s (currently the print icon is the *silx* one)
- `MaskScatterWidget`: depends on `MaskImageWidget`. Should we try to use `SilxMaskImageWidget` (different API)
=> [5.3] PlotWindow

PyMca5/PyMcaGui/plotting/MaskScatterWidget.py, PyMca5/PyMcaGui/plotting/MaskToolBar.py, PyMca5/PyMcaGui/plotting/RGBCorrelatorGraph.py, PyMca5/PyMcaGui/plotting/ScatterPlotCorrelatorWidget.py
Make the MaskScatterWidget use a silx plot. Closes #105.
This solution uses the current pymca interaction, with buttons in a small toolbar, instead of using the silx mask widget.
=> [5.3]MaskScatterWidget

doc/man/elementsinfo.1, doc/man/peakidentifier.1, doc/man/pymcaroitool.1
The file pattern contains `%03d` but the last two file names end in `%05d`, in the last example.
=> Inconsistency in man page for pymcaroitool?

PyMca5/PyMcaMath/sift/preprocess.cl
Variadic macros are not supported by all OpenCL compilers and may therefore generate compile-time errors.
Closes #133
=> sift: do not use variadic macro in preprocess.cl

PyMca5/PyMcaGui/io/hdf5/Hdf5NodeView.py
This closes #144 and should prevent most future API changes in the DataViews from impacting this feature of PyMca.
Now the only attribute in `silx.gui.data.NXdataWidgets.ArrayCurvePlot` that we depend on is _plot.
=> [NXdataView] don't duplicate API

PyMca5/PyMcaIO/ConfigDict.py
=> StringIO does not exist under Python 3.

PyMca5/PyMcaCore/Plugin1DBase.py, PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
This causes PyQt5 to be imported,  causing a PyQt4 / PyQt5 conflict for a reason yet unknown.
=> Remove silx.gui.qt import in Plugin1DBase

PyMca5/PyMcaGui/pymca/McaWindow.py
This PR is a bug fix for the silx branch. PyMcaQt does not provide `qt.Signal`.
=> Fix bug (qt.Signal does not always exist with PyQt)

PyMca5/PyMcaCore/NexusTools.py, PyMca5/PyMcaDataDir.py, package/debian9/changelog, package/debian9/rules
Allows to build debian  package on a machine with a previous version of PyMca already installed.
Changes for debian 9 package 5.3.1
=> Debian 9 package 5.3.1

PyMca5/PyMcaCore/StackBase.py, PyMca5/PyMcaGui/pymca/StackSelector.py, PyMca5/PyMcaIO/HDF5Stack1D.py, PyMca5/PyMcaMisc/PhysicalMemory.py
To use float64 data to deal with int32 data when a monitor is requested seems overkill.
This PR:
- Uses float32 when using a monitor
- Checks for **available** physical memory instead of installed physical memory under windows.
=> [ROI Imaging] Use float32 when using a monitor.

PyMca5/PyMcaGui/pymca/ExternalImagesWindow.py
Problem shown with matplotlib 2.2.2
The title was not updated but a resize was updating it. Setting the graph title prior to set the image solves the issue.
Closes #242
=> Set the title prior to update the image.

PyMca5/PyMcaGui/plotting/MaskImageWidget.py
This breaks image masking based on intensities (raises a TypeError):
https://github.com/numpy/numpy/commit/58e9e27c0c110f9be1558a53fb547dc1abc76fa4#diff-a42b7545751437baeae8a6e2dfaacd98
=> [gui] Remove numpy boolean subtraction from image mask.

PyMca5/PyMcaGui/math/SIFTAlignmentWindow.py, PyMca5/PyMcaMath/sift/__init__.py, PyMca5/PyMcaPlugins/ImageAlignmentStackPlugin.py
Closes #122 
On my machine it works fine with PY3, and shows correct results on PY2 but segfaults on exiting the demo code in `SIFTAlignmentWindow`. 
The segfault is most likely unrelated to sift, I believe I messed up my system when I uninstalled a lot of packages to do debian packaging (It also segfaults on PY2 when I run the demo code in `McaWindow`).
I will do a few more tests to try to solve the issue on my machine, before removing the WIP tag.
=> [silx]Use sift from silx

PyMca5/PyMcaGui/plotting/MaskImageWidget.py, PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py, PyMca5/PyMcaIO/EdfFile.py, PyMca5/PyMcaIO/MarCCD.py, PyMca5/PyMcaIO/PilatusCBF.py, PyMca5/PyMcaIO/TiffIO.py, PyMca5/PyMcaPlugins/SilxExternalImagesStackPlugin.py
In numpy 1.14, `fromstring` prints a deprecation warning when it is given binary data to process.
This PR uses `numpy.frombuffer` instead. Both functions have the same API in our use case, but `frombuffer` does not copy the data and returns a read-only array, so we need an additional copy.
The `numpy.frombuffer` function is available since at least numpy version 1.3.
=> Fix numpy.fromstring deprecation warning

PyMca5/PyMcaGui/physics/xrf/XRFMCPyMca.py
An application bundle is a directory, not a file.
Closes #255
=> Select a directory under MacOS.

PyMca5/PyMcaGui/pymca/ScanFitToolButton.py, PyMca5/PyMcaGui/pymca/ScanWindow.py
The resetzoom parameter in ScanWindow.addCurve was ignored.
This PR  closes #249, by not resetting the zoom in scan and MCA windows after a successful fit.
=> [GUI] Fix issue with resetzoom in ScanWindow

PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
Closes  #283
All curves are replotted every time, so the easy way to fix this was to clear the plot before plotting again, which resets colors and style.
=> [GUI] conserve plot lines and colors in McaAdvancedFit

PyMca5/PyMcaGui/PluginsToolButton.py
On object destruction, the callback is called with a param.
=> Fix signature of weakref callback

PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py, PyMca5/PyMcaGui/pymca/ScanWindow.py
This PR restores original save method in `McaAdvancedFit` instead of the using the silx save action. Closes #285.
It also renames the file filter in the `ScanWindow` save file dialog.
=> [save action] Restore original save method in McaAdvancedFit

PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
Closes #300. We need to explicitly set `resetzoom=False` in all `addCurve` calls.
=> [McaAdvancedFit] don't reset zoom when adding curves

PyMca5/PyMcaCore/Plugin1DBase.py, PyMca5/PyMcaGui/PluginsToolButton.py
If a plugin has a `activeCurveChanged(prev, next)` or a  `activeImageChanged(prev, next)` method, they should be connected with the corresponding plot signal.
=> Provide signals to plugins

PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py, PyMca5/PyMcaGui/plotting/PyMca_Icons.py, PyMca5/PyMcaGui/pymca/ScanWindow.py
Possible solution for #280. The icon substitution can be done in a single function called by each plot window.
=> Use PyMcaIcons insead of silx icons for some icons

PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
Closes #314  by redefining `McaAdvancedFit.setActiveCurve`.
=> don't unselect curve in McaAdvancedFit when clicking in the plot

PyMca5/PyMcaGui/pymca/PyMcaBatch.py, PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
The crashes due to concurrent access to the same file seem to be gone.
Just enabled the action and added a comment about the fact the stack can be loaded multiple times into memory.
=> Allow again multiple processes with a single HDF5 input file.

PyMca5/PyMcaCore/Plugin1DBase.py, PyMca5/PyMcaCore/Plugin2DBase.py, PyMca5/PyMcaCore/StackPluginBase.py
It was named PyMca and not PyMca5
=> Correct old default directory name

PyMca5/PyMcaGui/PyMcaQt.py
Workaround #378 because the problem comes from old ipython versions.
=> Give back priority to PyQt4 under Python 2.

PyMca5/PyMcaGui/physics/xrf/FastXRFLinearFitWindow.py, PyMca5/PyMcaPhysics/xrf/FastXRFLinearFitOutput.py, PyMca5/tests/__init__.py
Disable HDF5 output options when h5py is missing:
However the dependency of the main GUI on silx enforces h5py:
```python
File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-2.7/PyMca5/PyMcaGui/pymca/PyMcaMain.py", line 233, in <module>
from PyMca5.PyMcaGui.pymca import ScanWindow
File "/data/id21/inhouse/wout/dev/pymca/build/lib.linux-x86_64-2.7/PyMca5/PyMcaGui/pymca/ScanWindow.py", line 39, in <module>
from silx.gui.plot import PlotWindow
File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/rnice8/pymca/py27/local/lib/python2.7/site-packages/silx/gui/plot/__init__.py", line 64, in <module>
from .PlotWindow import PlotWindow, Plot1D, Plot2D  # noqa
File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/rnice8/pymca/py27/local/lib/python2.7/site-packages/silx/gu …
```
=> Resolve issue #418

PyMca5/PyMcaIO/NexusUtils.py, PyMca5/tests/NexusUtilsTest.py
Function asNxChar to create variable-length UTF-8 string:
- handles scalars and arrays
- handles ASCII byte-strings, extended ASCII byte-strings, unicode-strings, fixed-length numpy strings
- checks UTF-8 encoding (wasn't doing that before with custom dtype)
- extended ASCII bytes: either raise UnicodeDecodeError (default) or save as bytes (abuse HDF5 ASCII character set)
- behaves the same in python 2 and 3 (see tests)
Note: numpy 0d-array is saved as an HDF5 scalar.
=> Hdf5 string

PyMca5/PyMcaGraph/Plot.py, PyMca5/PyMcaGraph/backends/SilxBackend.py, PyMca5/PyMcaGui/plotting/PlotWidget.py, PyMca5/PyMcaGui/plotting/PlotWindow.py
This shows an alternative way to use silx within PyMca.
It works, but it seems more efficient to directly use the silx PlotWidget replacing the PlotWidget of PyMca.
=> Add silx backend as proof of concept

PyMca5/PyMcaIO/OmnicMap.py
Resolves #447 
Note: I do not have access to a Windows or Mac system to test this change, but the code logic has not changed for Windows, so that case should be fine. The only thing that should probably be tested is MacOS (`darwin`).
=> OmnicMap IO: remove windows check for binary file reading

.travis.yml
I wanted to enable GUI testing on travis (for comparing new vs. legacy PyMcaBatch code) and found that "Linux, py36, pyqt5" has leaking widgets. I haven't been able to reproduce the error locally. So use PySide2 or try to solve the issue?
=> [ci] enable Qt tests

PyMca5/PyMcaGraph/Plot.py, PyMca5/PyMcaGraph/backends/MatplotlibBackend.py, PyMca5/PyMcaGraph/backends/_patch_matplotlib.py, PyMca5/PyMcaGui/PyMcaQt.py, PyMca5/PyMcaGui/physics/xrf/ConcentrationsWidget.py, PyMca5/PyMcaGui/physics/xrf/FastXRFLinearFitWindow.py, PyMca5/PyMcaGui/physics/xrf/FitParam.py, PyMca5/PyMcaGui/physics/xrf/FitParamForm.py, PyMca5/PyMcaGui/physics/xrf/FitPeakSelect.py, PyMca5/PyMcaGui/physics/xrf/MaterialEditor.py, PyMca5/PyMcaGui/physics/xrf/MatrixEditor.py, PyMca5/PyMcaGui/physics/xrf/MatrixImage.py, PyMca5/PyMcaGui/plotting/PlotWidget.py, PyMca5/PyMcaGui/plotting/PyMca_Icons.py, PyMca5/PyMcaGui/plotting/Silx_Icons.py, PyMca5/PyMcaGui/pymca/McaWindow.py, PyMca5/PyMcaGui/pymca/PyMcaMain.py, PyMca5/PyMcaGui/pymca/QStackWidget.py, PyMca5/PyMcaGui/pymca/ScanWindow.py
Solves the crash on exit issue in many modules when using PyQt5. The condition to get rid of the crash is
to make sure no reference to a QApplication instance is kept.
A problem is that matplotlib.backends.backend_qt5agg holds a reference to it into a global variable (qApp) instead of using a weakref proxy. This has been reported to matplotlib, but it is not clear at all it will be solved because the crashes are random and not easy to reproduce.
=> [GUI] Crash on exit when using PyQt5

PyMca5/PyMcaGraph/backends/_patch_matplotlib.py
It was forcing to create a QApplication prior to import graphics related widget.
=> Make the matplotlib patch compatible with the QApplication not being instantiated yet

PyMca5/PyMcaGui/pymca/PyMcaBatch.py
The default installation of Python when selecting installation for All Users is "C:\Program Files"
=> [PyMcaBatch] Deal with spaces in the path of the executable

PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
Prevent the generation of files that cannot be read back.
=> [RGB Correlator] Cannot handle "," or ";" in label names

.travis.yml
Only makes sense on Linux for the old installations.
=> Do not test python 2 on Mac

PyMca5/PyMcaGui/physics/xas/XASNormalizationWindow.py, PyMca5/PyMcaMath/SNIPModule.py, PyMca5/PyMcaMath/fitting/SimpleFitUserEstimatedFunctions.py, PyMca5/__init__.py
They are not used anywhere in PyMca.
=> Remove "convenience" imports.

PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py, PyMca5/PyMcaPhysics/xrf/XRFBatchFitOutput.py
Solves bug in `McaBatch.onEnd` (make sure opening context is not required for just the filenames).
=> [outbuffer] no need for buffercontext when simply asking for filenames

PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py, PyMca5/PyMcaPhysics/xrf/XRFBatchFitOutput.py
Solve issue #489. The FOMs will always be saved. HDF5 will contain all of them, the other formats only the chisq. Note that this only goes for slow fitting, fast fitting does not produce the chisq.
=> [batchfit] force save FOMs (chisq only for non-hdf5 formats)

PyMca5/PyMcaGui/pymca/PyMcaMain.py, PyMca5/PyMcaGui/pymca/PyMcaPostBatch.py, PyMca5/PyMcaGui/pymca/RGBCorrelator.py, PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py, PyMca5/PyMcaIO/NexusUtils.py
This PR addresses issue #422 (only the RGB correlator).
I minimized refactoring:
- `RGBCorrelatorWidget.addFileList` loops and calls `_addSingleFile` which checks file formats and calls `_addEdfFile`, `_addHdf5File`, etc.
- remove file format checking from `PyMcaPostBatch` (redundant, didn't want to do it for HDF5 as well)
- deprecation warning for the public `RGBCorrelatorWidget.addBatchDatFile` method (calls `addFileList`)
HDF5 support is added to `RGBCorrelatorWidget`:
- If the file exists but the uri does not, it will prompt for a uri.
- I used `HDF5Widget.getUri` and `NexusUtils.getNdimDatasets`.
=> [rgb] add hdf5 support

PyMca5/PyMcaGui/physics/xrf/FastXRFLinearFitWindow.py, PyMca5/PyMcaGui/pymca/PyMcaBatch.py, PyMca5/PyMcaPhysics/xrf/XRFBatchFitOutput.py, PyMca5/tests/PyMcaBatchTest.py, PyMca5/tests/XRFBatchFitOutputTest.py
Solve issue #490.
Modify batch output from
```
map_xia00_0001_0000_0000_to_0004.h5::/map_xia00_0001_0000_0000_to_0004
map_xia00_0001_0000_0000_to_0004/map_xia00_0001_0000_0000_to_0004.edf
map_xia00_0001_0000_0000_to_0004/map_xia00_0001_0000_0000_to_0004.dat
...
```
to
```
map_xia00_0001_0000_0000_to_0004.h5::/map_xia00_0001_0000_0000_to_0004
IMAGES/map_xia00_0001_0000_0000_to_0004.edf
IMAGES/map_xia00_0001_0000_0000_to_0004.dat
...
```
=> [outbuffer] use 'IMAGES' as root directory for legacy formats

PyMca5/PyMcaPlugins/NormalizationPlugins.py
The McaWindow re-implements addCurve in such a way that detects if we are updating a curve. If the first curve replaces the others, then it has no way to detect we are updating a curve.
closes #517
=> Let the McaWindow handle the calibration.

PyMca5/PyMcaPhysics/xas/XASClass.py
This variable allocation is raising a KeyError in my case when try to access `k`. Without processing seems find.
Anyway those variables are never used later (or they are overwrite)
=> Remove unused variables

PyMca5/tests/PyMcaBatchTest.py
Last commit of #544 solved some crashes during tests on Mac.
Enable skipped tests under the Mac.
=> [CI] Update PyMcaBatchTest.py

PyMca5/PyMcaPhysics/xrf/ConcentrationsTool.py, PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
Error on issue #546 was due to the bad handling of old fit configuration files where attenuators did not have the funny filter information.
Besides that, a batch with concentrations where the first calculation was wrong was crashing the program.
=> Error on concentrations using old configuration files

PyMca5/PyMcaGui/physics/xrf/QtMcaAdvancedFitReport.py, PyMca5/__init__.py, changelog.txt
It seems matplotlib errors related to the use of logarithmic y axis are not always caught.
This PR tries to figure out what type of plot is appropriate (log or linear) if nothing has been requested.
=> [PyMcaBatch] More robust HTML report generation

PyMca5/PyMcaGui/pymca/PyMcaMain.py
The default was matplotlib due to an error on the name of the passed variable.
=> Default scatter backend should be OpenGL

PyMca5/Object3D/Object3DPlugins/ChimeraStack.py, PyMca5/PyMcaCore/PyMcaBatchBuildOutput.py, PyMca5/PyMcaGui/pymca/SilxGLWindow.py, PyMca5/tests/XRFBatchFitOutputTest.py
Closes #586.
Issue: Default h5py file mode will change from 'a' to 'r'.
Solution: Add `mode='a'` to all `h5py.File` calls which do not specify a mode (unless it can be read-only).
=> [h5py] always specify file mode

PyMca5/PyMcaPlugins/RegularMeshPlugin.py
Get rid of unnecessary and not always properly working code now that Bliss uses the SPEC convention for mesh scans.
=> Assume use of number of intervals

PyMca5/PyMcaIO/specfilewrapper.py
Sometimes there are errors related to the encodings. If that happens it is clear we are not dealing with a SPEC file.
=> [IO] In case of error reading the file it is clear it is not a SPEC file.

PyMca5/PyMcaGui/math/PCAWindow.py, PyMca5/PyMcaMath/mva/PCAModule.py, PyMca5/PyMcaMath/mva/PCATools.py
Give the user the choice to perform the PCA on the covariance matrix or the correlation matrix, the later being the covariance matrix scaled to the diagonal elements in order to have unit standard deviation.
=> [PCA] Allow to use covariance or correlation

PyMca5/PyMcaIO/HDF5Stack1D.py
When user selects spatial coordinates, they were ignored.
The current rationale, for a 3-dimensional dataset, is the following:
- 1 dataset selected as axis means the dataset is identified as channels. It must match the size of the stack 1D dimension
- 2 dataset selected as axes means the datasets are the spatial dimensions. They must match the corresponding dimensions of the data in size and order.
- 3 dataset selected as axes means the datasets are the dimensions of the data. They must match the corresponding dimensions of the data in size and order.
=> [ROI Imaging] Handle axes as dimensions

PyMca5/PyMcaIO/HDF5Stack1D.py, PyMca5/PyMcaIO/OlympusCSVFileParser.py, PyMca5/PyMcaIO/specfilewrapper.py
Perform file type identification using byte strings to avoid decoding errors.
close #655
=> [IO] Correct MacOS issues

PyMca5/PyMcaGui/pymca/QDataSource.py
.spe files with the degree symbol in the file name cannot be open due to encoding errors triggered by h5py although they can be opened by specfilewrapper.
=> Deal with non-ASCII symbols in the name

PyMca5/PyMcaIO/ArraySave.py
Current h5py master branch removed the backwards compatibility fid attribute.
=> [IO] Compatibility fid deprecated

PyMca5/PyMcaGui/plotting/PlotWindow.py
./site-packages/PyMca5/PyMcaGui/plotting/PlotWindow.py:1290: RuntimeWarning: overflow encountered in uint_scalars
deltaY = yw[-1] - yw[0]
=> [Plot] Prevent overflows using unsigned ints.

PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- pickradius with markers
- graph limits when having identical min and max values (i.e. single point plots)
=> [plot] Get rid of matplotlib warnings

PyMca5/PyMcaMath/SpecArithmetic.py
when doing the simple spec arithmetic I encountered a bug in the math which is only obvious for data with a few (1-2) points at the slope (plateau-like instead of gauss-like functions).
for finding the x-coordinates of the FWHM a `while` loop is run for the lower and upper side of the peak maximum to find the index of the first data point that is smaller than the half-max value.
in the subsequent linear interpolation one should then use one data point below and above the half-max value.
This PR fixes this issue for the upper side of the peak.
=> fix fwhm calculation

PyMca5/PyMcaGui/pymca/PyMcaMain.py, PyMca5/PyMcaGui/pymca/PyMcaPostBatch.py, PyMca5/PyMcaGui/pymca/RGBCorrelator.py, PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
Closes #729 
Add image shape to `pymcapostbatch` CLI:
```python
pymcapostbatch --shape=68,101 filename.h5::1.1/measurement
```
In addition the RGB correlator window is opened when no images are specified. Useful in case you want to specify the shape (with the "reshape" button) before loading images when launching the RGB correlator from the main GUI.
=> Rgb correlator apriori shape

PyMca5/PyMcaMath/mva/_cython_kmeans/default/kmeans.c, PyMca5/PyMcaMath/mva/_cython_kmeans/kmeans.pyx
kmeans under MacOS was not working because of trying to make a view of one array mixing different integer types.
This PR uses int32.
=> [mva] Prevent kmeans issues due to mismatched integer types.

PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
Avoids the problem reported in https://bugreports.qt.io/browse/QTBUG-5115
Without this modification, when selecting the description, the horizontal bar shifts and the first column is hidden.
=> [HDF5] HDF5Widget disable automatic scrolling

PyMca5/PyMcaIO/RenishawMap.py
It seems recent converters from the native .wxd file to .txt use a single line header.
=> [I/O] Deal with files containing a single line header.

PyMca5/PyMcaCore/RedisTools.py, PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py, PyMca5/PyMcaIO/BlissSpecFile.py
- Correct deprecation warning concerning the use of filter as keyword
- Adjust the number of points to the maximum of points in a counter
- Handle selection covering different masters by not raising an exception if the number of selected scans is above four. The selection is simply ignored.
=> [IO] Integrate beamline feedback

PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py, PyMca5/PyMcaGui/pymca/PyMcaBatch.py, PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
The risk appears when there is only one HDF5 file to fit and the output directory is the directory containing that file.
closes #800 
completes PR #802
=> Verify risk of overwriting input file when choosing output directory

PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
Get rid of error in calibration when clicking on an empty space after having already selected a peak.
=> Correct picking error on McaCalWidget

PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
`_lastMouse` attribute does not exist if the mouse was never pressed in the widget lifetime. This causes troubles e.g. when one sets current index (`setCurrentIndex()`) which leads to `emitSignal()`.
Protect `emitSignal()` against non existing `_lastMouse` attribute.
=> fix: protect `HDF5Widget.emitSignal()` when mouse was not pressed yet

PyMca5/PyMcaGui/pymca/PyMcaBatch.py, PyMca5/PyMcaPhysics/xrf/ConcentrationsTool.py
Error generating HTML report with concentrations selected reported at mailing list
https://sourceforge.net/p/pymca/mailman/message/37410891/
```
WARNING:__main__:ERROR on REPORT (<class 'KeyError'>, KeyError('',), <traceback object at 0x0000027FAC6F8A08>)
WARNING:__main__:''
--- Logging error ---
Traceback (most recent call last):
File "build\tmp\PyMcaBatch.py", line 1847, in onMca
File "build\tmp\PyMcaBatch.py", line 1935, in __htmlReport
File "C:\Program Files\PyMca 5.6.7\PyMca5\PyMcaGui\physics\xrf\QtMcaAdvancedFitReport.py", line 119, in writeReport
text = self.getText()
File "C:\Program Files\PyMca 5.6.7\PyMca5\PyMcaGui\physics\xrf\QtMcaAdvancedFitReport.py", line 168, in getText
text+=self.getConcentrations()
File "C:\Program Files\PyMca …
```
=> Correct HTML report generation

PyMca5/PyMcaCore/NexusTools.py
Some scans have the "scanned" positionner configured as a counter.
This modification will show "scanned" counters as first in the list for particular scans.
=> [NexusTools] Get scanned positioners account for special scans (fscan for the time being)

PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py, PyMca5/PyMcaIO/HDF5Utils.py, PyMca5/tests/HDF5UtilsTest.py
Iterating the HDF5 root (for example `h5file["/"].keys()`) can cause segfaults. Execute these calls in a subprocess.
=> [HDF5] Hdf5 segfault handling

PyMca5/tests/McaStackViewTest.py
@picca 
It aims to fix at the upstream side:
Debian Bug#1010258: python3-pymca5: flaky autopkgtest on i386
=> Relax equality condition under 32-bit

PyMca5/PyMcaData/HTML/MCA-HOWTO.html
On Fedora Workstation (both on 36 with PyMca-5.6.7-6.fc36.x86_64 and on 34 with PyMca-5.5.0-7.fc34.x86_64) the text links in the window:
PyMca -- Help -- MCA HOWTOs
do not jump to the anchors below.
=> fix anchors in MCA-HOWTO.html

PyMca5/PyMcaIO/specfile/include/locale_management.h, PyMca5/PyMcaIO/specfile/src/locale_management.c, setup.py
Harmonize use of strtod_l. It should be available on all supported OSes.
Makes SPECFILE_USE_GNU_SOURCE obsolete.
fixes #859
=> Clean up locale_management in specfile

PyMca5/PyMcaCore/NexusTools.py
ESRF uses top-level external links (NXentry level) pointing to top-level links with different name.
=> [HDF5] Deal with top-level entries being external links

PyMca5/PyMcaGui/misc/testutils.py, setup.py
Follows:
https://stackoverflow.com/questions/4414234/getting-pythons-unittest-results-in-a-teardown-method
closes #889
=> Adapt tests to python 3.11

PyMca5/PyMcaGui/io/hdf5/HDF5Info.py, PyMca5/__init__.py, changelog.txt, package/pyinstaller/pyinstaller.spec
Reported at the mailing list https://sourceforge.net/p/pymca/mailman/message/37695123/
- The module multiprocessing does not properly work with PyInstaller.
- Copy-paste error caught by PySide6 but not by the other bindings.
=> [GUI] Correct HDF5Widget issues

PyMca5/PyMcaGui/physics/xrf/StrategyHandler.py, PyMca5/PyMcaPhysics/xrf/ClassMcaTheory.py
- Do not limit the number of matrix iterations to 5.
- Allow lower intensity peaks.
=> [XRF] XRF fit improvements

PyMca5/PyMcaIO/OutputBuffer.py, PyMca5/PyMcaPhysics/xrf/FastXRFLinearFit.py, PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
Sometimes the user provides energy values and a calibration (0, 1, 0) or (0, 0.001, 0).
One cannot assume the x values are integers.
=> [McaAdvancedFitBatch] Account for the case the initial X values are energy values

PyMca5/PyMcaCore/McaStackExport.py, PyMca5/PyMcaCore/StackBase.py, PyMca5/PyMcaGui/pymca/StackSelector.py, PyMca5/PyMcaIO/BrukerBCF.py
This PR allows reading of bcf files, including energy calibration into the ROI Imaging Tool.
In case the map does not fit into memory, an automatic down sampling takes place.
For the time being, the data might need to be exported to HDF5 for full functionality.
The live_time of each pixel still has to be read.
=> [IO] Minimal support of bcf files

PyMca5/PyMcaIO/sps/Src/sps_lut.c
Implicit ints are a C language feature that was removed with the C99 language revision.  Future C compilers may default to a language mode which does not enable them, causing compilation to fail.
=> Avoid implicit int types in PyMca5/PyMcaIO/sps/Src/sps_lut.c

PyMca5/PyMcaIO/NexusUtils.py
When trying to save fit results in `/`, I got the following error:
```
RuntimeError: / is an instance of NXentry instead of NXroot
```
which felt odd to me (`/` is often `NXroot` and not `NXentry`).
A quick check in the code showed me that the NXclasses in the error message were indeed swapped. This PR fixes this.
=> Swap arg places in nxClassNeedsInit error message

PyMca5/PyMcaIO/RTXMap.py
Identify the sum spectrum because it has no motor positions while the other scans have them.
```
error opening an rtx file
Traceback (most recent call last):
File "PyMcaMain", line 1439, in __roiImaging
File "PyMca5\PyMcaGui\pymca\QStackWidget.py", line 630, in loadStack
stack = self.stackSelector.getStack()
File "PyMca5\PyMcaGui\pymca\StackSelector.py", line 181, in getStack
stack = RTXMap.RTXMap(filelist[0])
File "PyMca5\PyMcaIO\RTXMap.py", line 105, in __init__
positioners[mne][i] = motorPos[mneIdx]
IndexError: list index out of range
```
=> [IO] RTX Map. Ignore sum spectrum in processed maps.

PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
With the modification, it only changes tab when the current tab is MCA but there are no MCAs present.
closes #981
=> Do not change tab

PyMca5/PyMcaGui/io/ConfigurationFileDialogs.py, PyMca5/PyMcaGui/pymca/PyMcaBatch.py
If all `All files` was selected for the input file list, the fit configuration was also defaulting to `All files`
Add CSV to the list of predefined filters
=> [PyMcaBatch] Force default to cfg for the fit configuration file.

PyMca5/PyMcaMath/mva/NNMAModule.py, PyMca5/PyMcaPlugins/NNMAStackPlugin.py
Done by duplicating the amount of memory used.
=> [ROI Imaging] Support NNMA on stacks of images

PyMca5/PyMcaGui/physics/xrf/McaCalWidget.py, PyMca5/PyMcaGui/pymca/McaWindow.py, PyMca5/PyMcaGui/pymca/SilxMcaWindow.py
There was a comparison between string and integer triggering an error when moving from ID18 to ID14.
=> Handle ID18 MCA calibration under Python 3

PyMca5/PyMcaPhysics/xrf/SingleLayerStrategy.py
closes #1036
An exception may be used in future versions.
=> [XRF] Strategy. Do not use two groups of the same element.

PyMca5/PyMcaCore/RedisTools.py, package/pyinstaller/pyinstaller.spec
=> [packaging] Adapt to Pyinstaller 6.x.x bundles

LICENSE, package/cxfreeze/cx_setup.py, package/pyinstaller/PyMca.txt, package/pyinstaller/pyinstaller.spec
=> Suppress syntax warnings

PyMca5/PyMcaGui/io/hdf5/Hdf5NodeView.py, PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py, PyMca5/PyMcaGui/pymca/PyMcaImageWindow.py, PyMca5/PyMcaGui/pymca/RGBImageCalculator.py
=> [GUI] Add silx histogram action

appveyor.yml
- Use build
- Upgrade to python 3.12
=> [CI] Do not call setup.py

PyMca5/PyMcaGui/plotting/LegendSelector.py
To be replaced by `globalPosition)().toPoint()`
https://doc.qt.io/qt-6/qmouseevent-obsolete.html#globalPos
=> [GUI] QMouseEvent.globalPos deprecated in PyQt6

PyMca5/PyMcaIO/OutputBuffer.py
=> [XRF] Do not attempt to save as ASCII the derivatives.

PyMca5/PyMcaPhysics/xrf/PyMcaEPDL97.py
=> Make sure index is an scalar

PyMca5/PyMcaGui/plotting/McaROIWidget.py, PyMca5/PyMcaMath/PyMcaSciPy/signal/mediantools.c, PyMca5/PyMcaPlugins/ImageAlignmentStackPlugin.py
=> [build] Get the code compile under numpy 2.0

PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py, doc/source/customization/plugins/plugins1d.rst, doc/source/customization/plugins/stackplugins.rst
Closes warnings reported in #1083
=> [doc] Get rid of Sphinx warnings.

PyMca5/PyMcaGui/physics/xrf/EnergyTable.py
Allow to toggle the consideration as characteristic energy from the user interface via a double click on the cell.
=> [GUI] XRF Energy table characteristic energies

src/PyMca5/PyMcaGui/physics/xrf/EnergyTable.py
The old way of setting the palette did not work on recent PySide6. Style sheets work
=> [GUI] Scatter color not shown

.gitignore, src/PyMca5/PyMcaCore/NexusTools.py, src/PyMca5/PyMcaGui/io/hdf5/NexusInfo.py, src/PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
Needs https://github.com/vasole/pymca/pull/1087 first
=> Add motor info to QNexuswidget

src/PyMca5/PyMcaGui/plotting/MaskScatterWidget.py
The appropriate way to convert a hexadecimal string to integer is by using the built-in functionality of `int`. The `eval` function is insecure; if the input could possibly come from outside the program, no matter how indirectly, this creates a risk of an arbitrary code execution exploit. It's also much less efficient.
=> Avoid unnecessary use of eval (insecure)

.github/workflows/ci.yml, changelog.txt, src/PyMca5/PyMcaGui/physics/xrf/FitPeakSelect.py, src/PyMca5/PyMcaPhysics/xrf/Elements.py, src/PyMca5/PyMcaPhysics/xrf/MShell.py
Implemented in analogue manner to the L shell.
=> [XRF] Allow to fit M subshells separately

src/PyMca5/PyMcaPlugins/NNMAStackPlugin.py, src/PyMca5/PyMcaPlugins/PCAStackPlugin.py
Expected to solve issue #1101 for NNMA and PCA
=> [MacOS] [ROI Imaging] Rework threading mechanism

src/PyMca5/PyMcaGui/physics/xrf/ConcentrationsWidget.py, src/PyMca5/PyMcaGui/physics/xrf/EnergyTable.py, src/PyMca5/PyMcaGui/physics/xrf/FitParamForm.py, src/PyMca5/PyMcaMath/fitting/Gefit.py, src/PyMca5/PyMcaPhysics/xrf/ClassMcaTheory.py, src/PyMca5/PyMcaPhysics/xrf/FisxHelper.py
Some users have manually edited the cfg file without passing via the GUI.
The retained accuracy in the cfg file was higher than in the GUI, thus leading to equivalent but not identical results when comparing batch (full accuracy retained) and GUI (limited by %.6g text formatting)
The description is changed from %.6g (default for the format) to %.8g that is overkill but improves reproducibility.
=> [XRF] Discrepancies between GUI and Batch results

src/PyMca5/PyMcaCore/NexusDataSource.py, src/PyMca5/PyMcaCore/NexusTools.py, src/PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py, src/PyMca5/PyMcaIO/HDF5Utils.py, src/PyMca5/tests/HDF5UtilsTest.py
- Move and refactor the three copies of `h5py_sorting` to a single `PyMca5.PyMcaIO.HDF5Utils.sort_h5items` function
- Improve sorting by name by splitting on all non-numeric characters (if any)
- When sorting by title, start_time, etc. has duplicate values, fall back to sorting by name
=> use one single function to sort HDF5 items

src/PyMca5/PyMcaIO/HDF5Stack1D.py
XDatasetList was undefined in case of dynamically loading a stack not fitting into memory and saved by PyMca.
=> Undefined variable dynamically loading a ROI Imaging saved stack.

src/PyMca5/PyMcaIO/HDF5Stack1D.py
The code as it was written was only dealing with a single dataset of images.
This PR makes sure if multiple scans and datasets are selected, they are properly summed.
It falls back to the case the data were not fitting into memory that was lost when avoiding a loop.
=> [IO] Improve image stack handling

src/PyMca5/PyMcaIO/OutputBuffer.py
Closes #1123 
FYI the `OutputBuffer` is used by PyMca to send fit results to. The buffer takes care of allocating space in memory or HDF5 and saving the fit results in HDF5, EDF, TIF, DAT or CSV.
This bug concerns a pure in-memory space allocation: it does not ensure that each dataset is independent. So if I change the content of one dataset it does not affect another.
=> OutputBuffer datasets cannot be the same

src/PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
When click on dataset in the group it adds all datasets to the table. If one dataset is too long it does not fit QSpinBox which leads to fact that any dataset from the group could not be displayed.
Rare and funny bug. 
I suggest just to skip such long datasets as one will not "spin" over 2 billion of layers.
=> skip too long datasets to prevent crush
