silx-kit/pymca

- PyMca5/PyMcaGraph/backends/GLSupport/PlotImageFile.py
This is fixed by adding missing import
> Fix plot opengl backend save as image

- PyMca5/PyMcaIO/sps/Src/sps.c
- PyMca5/PyMcaIO/sps/Src/sps_py.c
Added methods putinfo and putmetadata in python wrapper.
> Spec shared memory

- PyMca5/PyMcaPhysics/xrf/ClassMcaTheory.py
- Remove unused code
- Reduce the options to reading an mca file and a fit configuration with optional plotting.
> Get rid of unused code and reduce number of used command line options.

- PyMca5/PyMcaCore/StackPluginBase.py
- PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaPlugins/FitStackPlugin.py
- PyMca5/PyMcaPlugins/ROIStackPlugin.py
- PyMca5/PyMcaPlugins/SilxExternalImagesStackPlugin.py
- PyMca5/PyMcaPlugins/SilxRoiStackPlugin.py
- PyMca5/PyMcaPlugins/XASStackNormalizationPlugin.py
Implement a stackClosed() method for plugins, to be notified by stack widget.
Should I implement this method for most plugins, to close all widgets when the main window is closed?
> stackClosed

- PyMca5/PyMcaGui/pymca/QStackWidget.py
Closes #70 
I tested it with the two recent ID24 test stacks. I made sure that a given pixel has the correct value after summing the master and slave pixels at the same location.
> "Merge slave" action

- PyMca5/PyMcaGui/io/SpecFileDataInfo.py
- PyMca5/PyMcaGui/misc/TableWidget.py
- PyMca5/PyMcaPlugins/MotorInfoWindow.py
> Copy table data

- PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py
- PyMca5/PyMcaGui/pymca/SilxExternalImagesWindow.py
- PyMca5/PyMcaIO/EDFStack.py
- PyMca5/PyMcaIO/SpecFileStack.py
- PyMca5/PyMcaPlugins/MotorInfoWindow.py
- PyMca5/PyMcaPlugins/SilxExternalImagesStackPlugin.py
- PyMca5/PyMcaPlugins/StackMotorInfoPlugin.py
This PR implements a plugin to show motor positions in a stack.
- HDF5 data files (implemented in #72)
> Motor positions in stack

- PyMca5/PyMcaGui/plotting/Q4PyMcaPrintPreview.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
> Fix encoding issue with python 3 SVG print preview

- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaPlugins/LoadPositionersStackPlugin.py
- PyMca5/PyMcaPlugins/StackNormalizationPlugin.py
Test the positioners dict and update info["positioners"]
> Implement setPositioners

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
Make Hdf5Widget compatible with SPEC files if `silx` is available
> Make Hdf5Widget compatible with SPEC files

- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaPlugins/LoadPositionersStackPlugin.py
- PyMca5/PyMcaPlugins/MotorInfoWindow.py
- PyMca5/PyMcaPlugins/StackMotorInfoPlugin.py
This PR adds the option to read motor positions from a SPEC file, and makes `StackBase.setPositioners` more permissive regarding the data shape (as long as the data size is good).
> Improve positioners loading

- PyMca5/PyMcaPlugins/ReverseStackPlugin.py
I tested it by checking the values on a couple of corner pixels before and after reversing.
> Sort positioners when reversing columns or rows

- PyMca5/PyMcaIO/HDF5Stack1D.py
Forces the use of floating point stack if a monitor used.
It makes sure monitor data are read as floating point.
Closes #82 
Closes #83
> Normalization

- PyMca5/PyMcaGui/pymca/QStackWidget.py
> Account for the used scale.

- PyMca5/PyMcaGui/pymca/ScanWindow.py
> Prevent the generation of long titles when using average action.

- PyMca5/PyMcaGui/io/QEdfFileWidget.py
- PyMca5/PyMcaGui/physics/xrf/McaCalWidget.py
- PyMca5/PyMcaGui/plotting/ColormapDialog.py
- PyMca5/PyMcaGui/plotting/MaskImageTools.py
- PyMca5/PyMcaGui/plotting/RGBCorrelatorGraph.py
Replace `PlotWidget` with the silx `PlotWidget`.
> [5.3] PlotWidget

- PyMca5/PyMcaGui/plotting/PlotWidget.py
> [5.3] Deprecation warning for PlotWidget

- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaPlugins/BackgroundScanPlugin.py
> Reimplement removeCurve at McaWindow level.

- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaIO/HDF5Stack1D.py
> Get correct list of entries containing a selection.

- PyMca5/PyMcaGui/pymca/ScanWindow.py
Fix bug when trying to add a curve when none is available
> [5.3] ScanWindow bug in _addSelection

- PyMca5/PyMcaGui/io/hdf5/Hdf5NodeView.py
This PR adds a plugin tool button to the 1D viewer in NXDataViewer.
Closes #99
> NXDataViewer with plugins

- PyMca5/PyMcaGui/io/hdf5/Hdf5NodeView.py
In silx < 0.7, non monotonic `x` array causes data to be added as scatter data, which is not compatible with curve plugins.
> [NXdataView] Add 1D data always as curve

- PyMca5/PyMcaGui/pymca/XMCDWindow.py
Closes #106 
It was significantly easier than in PR #49, because this time ScanWindow has a `dataObjectDict` attribute.
> [5.3]XMCDWindow

- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
- PyMca5/PyMcaGui/plotting/RGBCorrelatorGraph.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
Update the way MaskImageWidget interacts with the plots (RGBCorrelatorGraph and ProfileScanWindow)
> [5.3]MaskImageWidget plot API

- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
Use a silx _PlotWindow_ & _PrintPreview_ in `McaAdvancedFit`. Closes #104 and helps with #103.
> [5.3] McaAdvancedFit

- PyMca5/PyMcaGui/pymca/McaLegendselector.py
- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
Closes #114. Finalizes #103.
TODO: more testing, handle ROI events.
> [5.3]McaWindow

- PyMca5/PyMcaGui/__init__.py
- PyMca5/PyMcaGui/io/QEdfFileWidget.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
- PyMca5/PyMcaGui/plotting/ImageView.py
- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
- PyMca5/PyMcaGui/plotting/PlotWidget.py
- PyMca5/PyMcaGui/plotting/Q4PyMcaPrintPreview.py
- PyMca5/PyMcaGui/plotting/RGBCorrelatorGraph.py
- PyMca5/PyMcaGui/pymca/ExternalImagesWindow.py
- PyMca5/PyMcaGui/pymca/LegacyScanWindow.py
- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave.py
- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave1D.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
- PyMca5/PyMcaGui/pymca/XMCDWindow.py
Migrate `PrintPreview` to silx and fix new bugs related to previous migration to PlotWidget.
Closes #103
> [5.3]PrintPreview

- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaIO/OmdaqLmf.py
Remove the restriction of having just two slaves. Usability will depend on the amount of memory.
> Basic support of multiple slaves

- PyMca5/PyMcaIO/EdfFile.py
Closing parenthesis issue spotted by landscape.io, file already closed spotted by @t20100 : https://github.com/silx-kit/silx/pull/1520/files#diff-8656f877230c3e76a67491f378b42d4d
> fix a couple of bugs with EdfFile.GetPixel

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- Associate a tooltip to NXdata-aware items
- Associate a color to NXdata-aware items
- Implement an action on double-click
> [HDF5] NXdata support

- PyMca5/PyMcaPlugins/XASScanNormalizationPlugin.py
> [XASNormalization] Fix legend when it is a single word

- PyMca5/PyMcaCore/NexusDataSource.py
> Read the positions in analogous way to SPEC files.

- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/plotting/PlotWidget.py
- PyMca5/PyMcaGui/plotting/PlotWindow.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaNexusWidget.py
> Provide automatic selection table

- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
ScanWindow and McaWindow had troubles with scalar datasets.
Closes #159
> [HDF5] Support scalar datasets

- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
Clicking on the tree widget on the file name was giving an exception.
> [HDF5] Correct exception error message when clicking on root item.

- PyMca5/PyMcaGui/io/hdf5/Hdf5NodeView.py
This PR depends on silx PR  #1646
> [DataViewer] cleaner way to replace views

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaGui/io/QSpecFileWidget.py
- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/io/hdf5/HDF5McaTable.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidgetActions.py
- PyMca5/PyMcaGui/pymca/PyMcaImageWindow.py
- PyMca5/PyMcaGui/pymca/PyMcaNexusWidget.py
> SPECfile-like selection on HDF5 files

- PyMca5/PyMcaGui/math/fitting/QScriptOption.py
- PyMca5/PyMcaGui/math/fitting/SimpleFitAllGui.py
- PyMca5/PyMcaGui/math/fitting/SimpleFitConfigurationGui.py
- PyMca5/PyMcaGui/math/fitting/SpecfitConfigGui.py
- PyMca5/PyMcaMath/fitting/SimpleFitAll.py
- PyMca5/PyMcaMath/fitting/SimpleFitModule.py
- PyMca5/PyMcaMath/fitting/SpecfitFunctions.py
- PyMca5/PyMcaPlugins/FitAllCurvesPlugin.py
> Fit all curves

- PyMca5/PyMcaIO/TiffIO.py
Read back as strings instead of bytes under Python 3
> Tiffio update

- PyMca5/PyMcaPlugins/ConsolePlugin.py
- PyMca5/PyMcaPlugins/ConsoleStackPlugin.py
> Plugin as plt

- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/io/hdf5/HDF5McaTable.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
Update plot on counter selection even if scan is not changed.
> HDF5 automatic actions improved

- PyMca5/PyMcaPhysics/xrf/SingleLayerStrategy.py
> Obey flag and correct compound mass fraction calculation.

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaIO/HDF5Stack1D.py
- PyMca5/tests/StackInfoTest.py
Closes #185 
-  [x] Soft Links
-  [x] External Links
> Read MCA information though links

- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/pymca/QHDF5StackWizard.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/tests/StackInfoTest.py
> Stack Time info

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaGui/io/hdf5/HDF5McaTable.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
- PyMca5/PyMcaGui/plotting/_ImageProfile.py
Suggest to use ROI Imaging Tool.
> [HDF5] Only offer average or sum with multidimensional datasets selected as MCA 

- PyMca5/PyMcaMath/fitting/SimpleFitAll.py
- PyMca5/__init__.py
- changelog.txt
Update version number and changelog
> Prepare 5.3.0

- PyMca5/PyMcaGui/math/fitting/SimpleFitAllGui.py
- PyMca5/PyMcaGui/math/fitting/SimpleFitConfigurationGui.py
- PyMca5/PyMcaMath/fitting/SimpleFitAll.py
- PyMca5/PyMcaPlugins/FitAllCurvesPlugin.py
> Fit all plugin improvements

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/math/fitting/SimpleFitAllGui.py
- PyMca5/PyMcaMath/fitting/SimpleFitAll.py
- PyMca5/PyMcaPlugins/FitAllCurvesPlugin.py
- PyMca5/PyMcaPlugins/ImageAlignmentStackPlugin.py
>  FitAll bugs

- PyMca5/Object3D/Object3DRedBookFont.py
- PyMca5/Object3D/SceneGLWidget.py
> Use QOpenGLWidget with PyQt >= 5.4

- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
> Corrects HDF5 file selection problem in v5.3.0

- MANIFEST.in
- requirements.txt
> Full functionality dependency list.

- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/io/QEdfFileWidget.py
- PyMca5/PyMcaGui/io/QSourceSelector.py
- PyMca5/PyMcaGui/plotting/PyMca_Icons.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaMdi.py
QToolButton redefined in PyMcaQt
> Adjust size when using silx icons

- doc/source/_templates/localtoc.html
- doc/source/_templates/pagesource.html
- doc/source/conf.py
- doc/source/customization/index.rst
- doc/source/index.rst
- doc/source/tutorials.rst
Improvements related to the sidebar menu and sphinx warnings.
Closes #222
> Documentation TOC

- MANIFEST.in
- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/__init__.py
- changelog.txt
- doc/source/hdf5/index.rst
- doc/source/index.rst
- doc/source/modules/core/index.rst
- doc/source/modules/core/nexustools.rst
- doc/source/modules/index.rst
- doc/source/tutorials.rst
> Prepare release

- PyMca5/PyMcaIO/HDF5Stack1D.py
- PyMca5/tests/StackInfoTest.py
> Hdf5 toplevel crash

- doc/source/hdf5/index.rst
Just a few minor typos that I found while reading the HDF5 docs
> Fix minor typos in hdf5 doc

- doc/source/faq.rst
- doc/source/install.rst
This PR fixes titles, adds links.
> [doc] Improvement of FAQ

- PyMca5/PyMcaIO/EdfFile.py
Problem described in https://github.com/silx-kit/silx/issues/1820
> Make sure integer division is used.

- PyMca5/PyMcaCore/Plugin1DBase.py
- PyMca5/PyMcaCore/StackPluginBase.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/__init__.py
Closes #257 
The code was duplicated in `PyMcaMain`. `FisxHelper` was already using the proper API.
> Settings dir

- .travis.yml
- PyMca5/tests/XrfTest.py
- ci/travis_osx.sh
- setup.py
It seems the default is python 3.7
> [CI] Specify python version via environment variable

- .travis.yml
- PyMca5/PyMcaGui/PyMcaPrintPreview.py
- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/plotting/PlotWidget.py
- PyMca5/PyMcaGui/plotting/PyMca_Icons.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/__init__.py
- PyMca5/scripts/edfviewer
- PyMca5/scripts/elementsinfo
- PyMca5/scripts/mca2edf
- PyMca5/scripts/peakidentifier
- PyMca5/scripts/pymca
- PyMca5/scripts/pymcabatch
- PyMca5/scripts/pymcapostbatch
- PyMca5/scripts/pymcaroitool
- PyMca5/scripts/rgbcorrelator
- changelog.txt
- doc/man/pymca.1
- doc/man/pymcaroitool.1
- setup.py
Minor version to address build issues under python 3.7 with previous version
> Prepare 5.3.2 release

- PyMca5/PyMcaGui/plotting/PlotWindow.py
- PyMca5/PyMcaGui/pymca/LegacyScanWindow.py
- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave.py
> Do not use obsolete grabWidget method

- PyMca5/PyMcaGui/physics/xrf/EnergyTable.py
Apparently some modifications were lost
> Collection of commits lost when merging the silx branch

- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
Restore graphics save options in PyMca using `QPyMcaMatplotlibSaveDialog`
Closes #271
> restore graphicsSave

- PyMca5/PyMcaGui/pymca/QHDF5StackWizard.py
- PyMca5/PyMcaIO/ArraySave.py
> NXdata new style

- doc/source/index.rst
- doc/source/recipes.rst
- doc/source/recipes/recipescode/GenerateHDF5Stack.py
- doc/source/recipes/xrfembedpyqt.rst
- doc/source/recipes/xrfhdf5stack.rst
- doc/source/tutorials.rst
- Embedding PyMca
- Writing HDF5 stacks of spectra
> Add some commonly requested recipes.

- doc/source/recipes/xrfhdf5stack.rst
This is just a patch, more realistic numbers should be used.
> Correct numbers

- PyMca5/PyMcaData/HTML/AdvancedAlignmentScanPlugin.html
- PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py
- doc/source/customization/plugins/plugins1d.rst
> [doc] AdvancedAlignmentScanPlugin

- PyMca5/PyMcaGui/io/QEdfFileWidget.py
- PyMca5/PyMcaGui/physics/xrf/McaCalWidget.py
- PyMca5/PyMcaGui/plotting/MaskScatterWidget.py
- PyMca5/PyMcaGui/plotting/RGBCorrelatorGraph.py
- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
- PyMca5/PyMcaGui/pymca/SumRulesTool.py
Closes #279 
Done: 
- ScanWindow
- McaWindow
- RGBCorrelatorGraph & MaskImageWidget
- McaAdvancedFit
TODO: 
- ? (TODO)
> [plot] Show "copy" action

- PyMca5/PyMcaPhysics/xrf/Elements.py
- PyMca5/tests/ElementsTest.py
If an element was repeated, it was taking always the first appearance of it.
> Deal with repeated elements. Closes #298

- PyMca5/PyMcaGui/__init__.py
> Prevent undesired import of PyQt5

- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedTable.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaPlugins/optional/TaurusPlugin1D.py
- Taurus is PyQt4 only and requires the api 2 for many things
- qtpy can have side effects on applications despite not using it!
> Modifications for Taurus Plugin compatibility

- PyMca5/PyMcaCore/Plugin2DBase.py
- PyMca5/PyMcaGui/PluginsToolButton.py
- PyMca5/PyMcaGui/io/hdf5/Hdf5NodeView.py
- PyMca5/PyMcaPlugins/Medfilt2DPlugin.py
Addresses #215 
TODO: 
- add a sample plugin
- testing
> Plugin2DBase

- PyMca5/PyMcaGui/PluginsToolButton.py
> fix toggling debug mode in plugin menu

- PyMca5/PyMcaIO/specfile/src/sfinit.c
https://github.com/silx-kit/silx/pull/2111
> Prevent specfile crash opening empty file

- PyMca5/PyMcaGui/math/StripBackgroundWidget.py
> Get rid of deprecation warnings

- PyMca5/PyMcaGui/pymca/PyMcaMain.py
> Provide access to steel spectrum and configuration.

- PyMca5/PyMcaGui/physics/xrf/McaCalWidget.py
> [McaCalWidget] don't ignore manual editing in the "save as" combobox

- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
> [McaAdvancedFit] Force RightDockWidgetArea with silx < 0.9.0

- PyMca5/PyMcaIO/LispixMap.py
- The specifications state the keywords are case insensitive.
> [IO] Lispix format: make sure to be case insensitive

- PyMca5/PyMcaPhysics/xrf/FisxHelper.py
- Fill the cache of the elements requested and those found in the attenuators
- Add a cache flag to the getMultilayerFluorescence function
> Cache improvements

- PyMca5/PyMcaGui/pymca/McaSimpleFit.py
- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/ScanFitToolButton.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
closes #347 (print buttons bugs)
> Print bugs

- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave.py
Backend was hardcoded in QPyMcaMatplotlibSave
Close #354
> fix matplotlib import

- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave.py
- PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py
> Correct advanced alignment plugin

- doc/source/install.rst
> document installation from conda-forge

- PyMca5/PyMcaPlugins/MaskScatterViewPlugin.py
- appveyor.yml
Addresses #346 
The matplotlib backend seems to be close to its limits when displaying the ch09 stack as a scatter.
> Mask Scatter View plugin

- PyMca5/PyMcaPlugins/Medfilt2DPlugin.py
Closes #360 and fixes a few other glitches.
> Medfilt2d bug

- PyMca5/PyMcaCore/NexusTools.py
Add convenience functions to retrieve groups or paths to groups matching a certain NXclass down to a given path.
> Add convenience functions

- PyMca5/PyMcaCore/LoggingLevel.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
> Actually set the logging level.

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
> Support default attribute at any level.

- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
> Make mask more visible on colormaps different from temperature

- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
> Correct attribute error and MacOS issue

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
> Deal with underscore in name

- package/debian8/changelog
- package/debian8/rules
- package/debian9/changelog
- package/debian9/rules
It works for debian 8. We have not managed to do the debian 9 packaging yet.
> debian packaging for 5.4.1

- PyMca5/PyMcaGui/physics/xrf/EnergyTable.py
> Deal with undetermined number of columns in the energy table.

- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
> Do not prepend "y" to the legend.

- PyMca5/PyMcaCore/NexusDataSource.py
@woutdenolf 
Prevent copy.deepcopy error in ScanWindow because of positioner values containing objects instead of numbers.
> [HDF5] Deal with exotic positioners .

- PyMca5/PyMcaGui/io/PyMcaFileDialogs.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
> [GUI/io] Respect nativefiledialogs setting

- PyMca5/PyMcaGui/pymca/ScanWindow.py
closes #385 
Requires silx 0.10.0 to be operational.
> Recover comment in print preview.

- PyMca5/PyMcaGui/pymca/ScanWindow.py
> Replace removed updateFromDataObject method.

- doc/man/pymca.1
- package/desktop/edfviewer.desktop
- package/desktop/elementsinfo.desktop
- package/desktop/peakidentifier.desktop
- package/desktop/pymca.desktop
- package/desktop/pymcapostbatch.desktop
- package/desktop/pymcaroitool.desktop
> Add Comment field.

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Info.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- h5py .value related warnings
- silx PyQt4 usage related warnings when under python 2.
> Reduce the amount of warnings

- PyMca5/PyMcaIO/specfile/src/sftools.c
> Wrong value tested

- PyMca5/PyMcaGui/plotting/PlotWindow.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
> Restore missing method.

- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
> Recover ScanWindow saving options.

- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
> Deal with selection of two top level datasets.

- PyMca5/PyMcaPlugins/StackNormalizationPlugin.py
Useful to convert FTIR transmission data to absorption.
> Simple transmission to absorption converter.

- PyMca5/PyMcaGui/plotting/PlotWidget.py
Makes sure the backend has the appropriate parent.
> Pass a parent to the backend

- PyMca5/PyMcaGraph/backends/SilxBackend.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
- PyMca5/tests/McaAdvancedFitWidgetTest.py
Allow to test the different backends if the dependencies are met.
- matplotlib
- OpenGl
- silx-mpl
- silx-gl
> Test up to four backends.

- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaPlugins/StackMotorInfoPlugin.py
> Motor info plugin

- PyMca5/PyMcaIO/HDF5Stack1D.py
Allow intermediates to be up to 40% of available memory instead of just 500 MBytes.
closes #446
> [HDF5] Less conservative reading approach.

- PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
- PyMca5/PyMcaIO/MarCCD.py
- PyMca5/PyMcaIO/OmnicMap.py
- PyMca5/PyMcaIO/PilatusCBF.py
- PyMca5/PyMcaIO/SupaVisioMap.py
- PyMca5/PyMcaIO/TiffIO.py
- Update comments
- Use rb mode for all platforms dealing with SupaVisio maps.
> [IO] No distinction windows/linux in SupaVisio maps

- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
The usage of OpenGL was disabled in PyMcaMain.py
> [PySide2] Enable OpenGL usage

- PyMca5/PyMcaGui/pymca/PyMcaMain.py
> Get rid of some code dating back to when WindowsXP was mainstream!!!!

- PyMca5/Object3D/Object3DBase.py
- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/physics/xas/XASWindow.py
- PyMca5/PyMcaGui/physics/xrf/ConcentrationsWidget.py
- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave1D.py
> Typos and warnings

- PyMca5/PyMcaDataDir.py
> Make sure use regular string in PyMcaDataDir.py

- PyMca5/PyMcaGui/misc/QIPythonWidget.py
https://github.com/ipython/ipykernel/issues/370
> Console not working after unhandled exception

- .travis.yml
- appveyor.yml
silx 0.10.1 does not work with matplotlib 3.1.0
> [CI] pinpoint matplotlib version due to silx

- .travis.yml
- appveyor.yml
> [CI] Use silx from daily builds

- .travis.yml
- PyMca5/PyMcaGui/misc/testutils.py
- PyMca5/tests/TestAll.py
Seen relatively often under windows and due to keeping a QApplication handle.
> [CI] Prevent random crash when exiting the tests.

- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
> [GUI] Workaround matplotlib error when removing markers.

- PyMca5/PyMcaPlugins/FastXRFLinearFitStackPlugin.py
Forgot to update `FastXRFLinearFitStackPlugin` for `OutputBuffer` API change.
> [fastfit] GUI bug

- PyMca5/PyMcaGui/math/PCADialog.py
- PyMca5/PyMcaIO/NexusUtils.py
- PyMca5/PyMcaIO/OmnicMap.py
- PyMca5/PyMcaIO/SupaVisioMap.py
- PyMca5/PyMcaMath/fitting/StackSimpleFit.py
- PyMca5/PyMcaMath/mva/NNMAModule.py
- PyMca5/PyMcaMath/mva/PCAModule.py
- PyMca5/PyMcaMisc/ProfilingUtils.py
- PyMca5/PyMcaPhysics/xrf/McaStackView.py
- PyMca5/PyMcaPhysics/xrf/XRFBatchFitOutput.py
- PyMca5/tests/XRFBatchFitOutputTest.py
- PyMca5/tests/XrfData.py
> [BatchFit] Replace spaces by underscores

- PyMca5/PyMcaIO/ConfigDict.py
> [ConfigDict] Only import h5py when needed.

- PyMca5/PyMcaPhysics/xrf/XRFBatchFitOutput.py
> [outbuffer] overwrite warnings to info

- PyMca5/PyMcaGui/io/QEdfFileWidget.py
- PyMca5/PyMcaGui/plotting/PlotWidget.py
- PyMca5/PyMcaGui/pymca/EdfFileSimpleViewer.py
> [edfviewer] Prevent flashing when selecting differnt file

- PyMca5/tests/ConfigDictTest.py
One test was not run in manual mode.
> Add missing test.

- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/SilxGLWindow.py
- Resolve conflicts of PR #377
- Autoscale handling
> SilxGLWindow

- PyMca5/PyMcaCore/StackROIBatch.py
- PyMca5/tests/ROIBatchTest.py
- PyMca5/tests/__init__.py
> [ROI Imaging] Correct ROI batch plugin calculations

- PyMca5/PyMcaGui/plotting/PlotWindow.py
> [ROI Widget] Avoid the need to use two clicks

- PyMca5/PyMcaGui/io/QSpecFileWidget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/SilxScatterWindow.py
> Add ScatterView

- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaPlugins/MultipleScanToMeshPlugin.py
> [Plugins] Fix multiple scan to mesh plugin

- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
> [HDF5] Recover the plot of images with dimensions.

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/math/SIFTAlignmentWindow.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaPlugins/ImageAlignmentStackPlugin.py
https://github.com/silx-kit/silx/issues/2640
> [HDF5] Support SWMR access while file being written.

- PyMca5/PyMcaIO/NexusUtils.py
> [nexus] exception type change for existing hdf5 dataset

- PyMca5/PyMcaGui/plotting/PlotWindow.py
> [ROI Imaging] Delete middle marker when using ICR.

- PyMca5/PyMcaPhysics/xas/XASClass.py
fix the case where only one point is picked from `_getRegionsData`.
> [PyMcaPhysics][XASClass] fix normalize

- PyMca5/PyMcaGui/pymca/McaCalibrationControlGUI.py
> [McaWindow] Use PyMcaFileDialogs abstraction

- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
Issue #540.
HTML tries to save before the XRF OutputBuffer does. As a result, it needs to do a recursive mkdir
> [batchfit] recursive mkdir

- PyMca5/tests/McaAdvancedFitWidgetTest.py
> Disable OpenGL tests on arm32 platform to simplify debian packaging

- PyMca5/PyMcaGui/plotting/McaROIWidget.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
> [GUI] Allow to sort ROI table by ROI name or from value.

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaPlugins/RegularMeshPlugin.py
- PyMca5/tests/PyMcaBatchTest.py
> [Plugins] Regular Mesh plugin

- PyMca5/PyMcaPlugins/RegularMeshPlugin.py
Difference of one point when comparing to SPEC
> [RegularMeshPlugin] Deal with bliss way of calculating the coordinates.

- PyMca5/PyMcaPlugins/RegularMeshPlugin.py
Show the expected absolute coordinates and not the relative ones.
> [RegularMeshPlugin] Absolute coordinates in relative meshes

- PyMca5/PyMcaGui/pymca/SilxScatterWindow.py
> Add axes labels to the scatter plot.

- PyMca5/PyMcaCore/McaStackView.py
- PyMca5/PyMcaGui/pymca/ExternalImagesStackPluginBase.py
- PyMca5/PyMcaIO/OutputBuffer.py
> Remove explicit six dependency

- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
1. Fix issue #551: the EDF viewer's `setFileList` takes a long time to finish so do not launch the viewer in the main thread.
2. Fix bug: the EDF viewer did not show up after a single process fit (because we forced the outputdir back to "IMAGES" a while back and I didn't adapt this here).
> [batchfit] EDFviewer as independent process

- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaPostBatch.py
- changelog.txt
> [PyMcaBatch] Deal with spaces in the configuration file path

- PyMca5/PyMcaIO/OutputBuffer.py
Set the logging level to info instead of warning on choices.
> [PyMcaBatch] No warnings on choices

- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
> Properly terminate the thread

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaCore/NexusTools.py
This PR prepares the use of the silx I/O API in the feature for new data formats.
> [io] Use of h5py API as generic reader

- PyMca5/PyMcaIO/ConfigDict.py
> Deal with deprecation warning.

- PyMca5/Object3D/Object3DPlugins/ChimeraStack.py
> correct syntax error

- PyMca5/PyMcaGui/pymca/PyMcaMain.py
On MacOS the saved geometry was not respected.
> Fix main window geometry under MacOS

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaPostBatch.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaIO/__init__.py
- PyMca5/__init__.py
> [HDF5] Prepare for new hdf5plugin

- PyMca5/PyMcaGui/physics/xrf/AttenuatorsTable.py
> Reduce the size of the material editor when using large text.

- PyMca5/PyMcaIO/HDF5Stack1D.py
> Handle broken NXentry links

- PyMca5/PyMcaPlugins/PCAStackPlugin.py
Enable ICA calculations when dealing with a stack of spectra.
> [BUG] ICA calculations not possible.

- PyMca5/PyMcaPhysics/xrf/XRFMC/XRFMCHelper.py
This has been GTK for +3 years now...
> XRFMCHelper: use GTK instead of GTK2

- PyMca5/PyMcaGui/physics/xrf/MaterialEditor.py
- PyMca5/PyMcaIO/ConfigDict.py
- PyMca5/tests/ConfigDictTest.py
> [IO] Handle % character in keys and values

- PyMca5/PyMcaPlugins/BackgroundScanPlugin.py
When a curve is calibrated one has to use the same name for the curve with the subtracted background in order to properly handle the calibration.
> Calibrated curves need special treatment.

- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaIO/HDF5Stack1D.py
In case of multiple files or multiple scans it only reads the positioners of the first selection. It assumes the actual filtering will take place on the number of pixels when setting the stack.
> [ROI Imaging] Automatically read positioners from HDF5 files

- PyMca5/PyMcaGraph/PluginLoader.py
> Use importlib instead of imp.

- PyMca5/PyMcaGui/pymca/SilxScatterWindow.py
When changing visualization TAB the scatter options were lost.
> [GUI] Scatter. Keep user visualization settings

- PyMca5/PyMcaGui/math/NNMAWindow.py
- PyMca5/PyMcaMath/mva/NNMAModule.py
- PyMca5/PyMcaMath/mva/PCAModule.py
- PyMca5/PyMcaPlugins/NNMAStackPlugin.py
- PyMca5/PyMcaPlugins/PCAStackPlugin.py
> [MVA] NNMA. Allow the calculation on selected regions.

- PyMca5/PyMcaIO/specfilewrapper.py
> [IO] Speed up SPEC file detection.

- PyMca5/PyMcaMath/mva/NNMAModule.py
- PyMca5/PyMcaMath/mva/PCATools.py
- PyMca5/tests/PCAToolsTest.py
> [mva] NNMA should work with no regions defined.

- PyMca5/PyMcaGui/pymca/ScanWindow.py
- PyMca5/PyMcaGui/pymca/StackPluginResultsWindow.py
- PyMca5/PyMcaGui/pymca/StackSelector.py
- PyMca5/PyMcaGui/pymca/StackXASBatchWindow.py
- PyMca5/PyMcaIO/ArraySave.py
- PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py
- PyMca5/PyMcaPlugins/ImageAlignmentStackPlugin.py
- PyMca5/PyMcaPlugins/StackAxesPlugin.py
- PyMca5/PyMcaPlugins/StackNormalizationPlugin.py
> [PCA, NNMA] Possibility to save all vectors at once

- PyMca5/__init__.py
- changelog.txt
> Update version and changelog.txt

- PyMca5/PyMcaCore/StackROIBatch.py
- PyMca5/PyMcaGui/plotting/McaROIWidget.py
- PyMca5/PyMcaGui/pymca/StackROIBatchWindow.py
- PyMca5/PyMcaIO/ConfigDict.py
Implemented for ROI batch and MCA ROI Table.
closes #633
> Handle ROI configurations from HDF5 files

- appveyor.yml
> [CI] Change Visual Studio Image

- PyMca5/PyMcaGui/physics/xrf/StrategyHandler.py
> [XRF] Extend Single Layer Strategy to 15 compounds.

- PyMca5/PyMcaPhysics/xrf/ClassMcaTheory.py
> [XRF] Single Layer Strategy. Restore old configuration in case of error.

- PyMca5/PyMcaMath/ImageRegistration.py
Crop indices expected to be integers.
> [Math] Make sure returned values are integers

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
> [HDF5] Handle multiple files with same entries

- PyMca5/PyMcaGui/pymca/QStackWidget.py
> [ROI Imaging] Do not close master stack when closing the slaves

- PyMca5/PyMcaMath/fitting/SimpleFitAll.py
> [Plugin] FitAllCurves. Create a summary table with the fit results.

- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/SilxScatterWindow.py
> Correr scatter bugs

- PyMca5/PyMcaPlugins/MedianFilterScanDeglitchPlugin.py
- PyMca5/PyMcaPlugins/MotorInfoWindow.py
- PyMca5/PyMcaPlugins/MultipleScanToMeshPlugin.py
Identify header motor and motor to energy conversion.
> [Plugin] Support CHESS RIXS multiple scans 

- .travis.yml
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
> [CI] Use fisx wheel without cython

- PyMca5/PyMcaIO/BAXSCSVFileParser.py
> [IO] Support Tracer 5 CSV Simple and Complete

- PyMca5/PyMcaGui/pymca/PyMcaImageWindow.py
Take row name and column name from selection.
> [GUI] PyMcaImageWindow use appropriate labels.

- .travis.yml
- PyMca5/PyMcaGraph/Colormap.py
- PyMca5/PyMcaGraph/backends/GLSupport/PlotImageFile.py
- PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
- PyMca5/PyMcaIO/EdfFile.py
- PyMca5/PyMcaIO/PilatusCBF.py
- PyMca5/PyMcaIO/TiffIO.py
> Use tobytes instead of the tostring alias.

- PyMca5/PyMcaIO/BAXSCSVFileParser.py
> [IO] Bruker AXS format. The Complete CSV was misinterpreted.

- PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
- PyMca5/PyMcaGui/pymca/RGBImageCalculator.py
The displayed title was that of the previous image.
> Make sure the displayed title is correct.

- PyMca5/PyMcaGui/pymca/LegacyPyMcaBatch.py
- appveyor.yml
Sometimes whn running the batch tests there are windows left open. Identify if they are legacy or not.
> When testing, identify the legacy windows.

- PyMca5/PyMcaIO/ArtaxFileParser.py
- PyMca5/PyMcaIO/RTXMap.py
- PyMca5/PyMcaPlugins/MaskScatterViewPlugin.py
- Reshape in case of regular maps
- Initialize MaskScatterView Plugin
> [ROI Imaging] Improved support of Artax maps

- PyMca5/PyMcaPlugins/MultipleScanToMeshPlugin.py
> [Plugin] Disable CHESS specific code.

- ci/travis_osx.sh
The previous link was redirecting.
> [CI] Update download link

- PyMca5/PyMcaGui/math/fitting/Parameters.py
- PyMca5/PyMcaGui/physics/xrf/PeakTableWidget.py
- PyMca5/PyMcaGui/pymca/TomographyRecons.py
> Correct installation warnings

- PyMca5/PyMcaIO/EdfFile.py
> [IO] EdfFile reopen file in append mode

- .travis.yml
- PyMca5/PyMcaCore/McaStackExport.py
- PyMca5/PyMcaCore/McaStackView.py
- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/tests/McaStackExportTest.py
This PR aims at generating an HDF5 file with the appropriate layout to store and read back all the information that can be read by the program.
It should at least partially address issues #89 and #81
> [ROI Imaging] Export the stack in HDF5 format

- PyMca5/PyMcaPhysics/xrf/XRFMC/XRFMCHelper.py
> Create script using text and not bytes

- PyMca5/PyMcaCore/McaStackExport.py
- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaIO/HDF5Stack1D.py
Allow to save and to retrieve stack, calibration, time, positiones and scales (if any) in such a way that information can be retrieved selecting a single dataset.
> [ROI Imaging] Save and load scales if present

- .travis.yml
- PyMca5/PyMcaGraph/backends/SilxBackend.py
addItem accepts a single unnamed argument.
> [silx backend] Add compatibility with silx 0.13

- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
> [MatplotlibBackend] Use pickradius instead of a value for picker.

- PyMca5/PyMcaGui/pymca/StackPluginResultsWindow.py
> [NNMA] Make sure the current title is shown.

- PyMca5/PyMcaCore/NexusDataSource.py
It does so by stripping excess points. A lot of things may fail downstream (ex. motors associated to curves)
closes #706
> [plot] Handle 1D plots of HDF5 datasets of different length

- PyMca5/PyMcaCore/RedisTools.py
It was taking 30 seconds on ID10. This is 20 times faster.
> [bliss] Get session filename was taking too long

- PyMca5/PyMcaCore/RedisTools.py
- PyMca5/PyMcaCore/SpecFileDataSource.py
- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaGui/io/QSourceSelector.py
- PyMca5/PyMcaGui/io/QSpecFileWidget.py
- PyMca5/PyMcaGui/pymca/QDataSource.py
- PyMca5/PyMcaIO/BlissSpecFile.py
- PyMca5/PyMcaIO/specfilewrapper.py
- PyMca5/PyMcaMath/fitting/specfit/snip3d.c
It allows to inspect the last scans as SPEC files.
> [bliss] Wrap redis data as SpecFile

- PyMca5/PyMcaMath/SpecArithmetic.py
check if the data is peak- or step-like.
Calculate the gradient of step-like data and recalculate the half-max value
> automatic step-like data detection

- PyMca5/PyMcaIO/BlissSpecFile.py
On ID26 computer reading each scan takes 0.250 seconds. This very simple cache saves around one second when selecting the last scan in the interface.
> Implement a simple cache to avoid multiple readouts.

- PyMca5/PyMcaCore/RedisTools.py
- PyMca5/PyMcaIO/BlissSpecFile.py
To get the number of lines reading one channel is enough.
> [Bliss] Speed up instantiation

- PyMca5/PyMcaMath/SpecArithmetic.py
II just forgot to add two lines of code. sorry for the inconvinience
> fix bug in FWHM calculation

- PyMca5/PyMcaCore/RedisTools.py
bliss.bliss_info is ['1', '5', '0'] on ID26
bliss.bliss_info is ['id10'] on ID10
> [bliss] bliss_info not reliable

- PyMca5/PyMcaPhysics/xrf/FastXRFLinearFit.py
Useful for several things, but mostly to debug bad fits.
> [fastfit] add peak profiles to diagnostics

- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
- PyMca5/PyMcaGui/plotting/_ImageProfile.py
- PyMca5/PyMcaGui/pymca/XMCDWindow.py
- PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py
- PyMca5/PyMcaPlugins/MultipleScanToMeshPlugin.py
- PyMca5/PyMcaPlugins/SilxExternalImagesStackPlugin.py
> [linspace] Make sure third argument is an integer

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
Prevent uncaught exception when displaying the tree.
closes #732
> [HDF5Widget] Try to make file introspection more robust.

- PyMca5/__init__.py
- changelog.txt
- Update changelog
- Update version
> Prepare 5.6.0 release.

- PyMca5/PyMcaGui/pymca/RGBImageCalculator.py
- PyMca5/PyMcaMath/mva/KMeansModule.py
> [mva] Subtract feature minimum prior to scale. 

- PyMca5/PyMcaGui/math/SGWindow.py
> [SGWindow] Map derivatives to the right axis.

- PyMca5/PyMcaGui/io/QSourceSelector.py
- setup.py
It would miss seldom used OpenGl visualization but main features of the program will be there
closes #704
> [build] Allow build from source in debian/ubuntu without mesa-common-dev

- PyMca5/PyMcaGui/pymca/SilxScatterWindow.py
Many thanks to @t20100 
Partially addresses #743
> [GUI] Scatter plot keep track of last used settings

- PyMca5/PyMcaGui/math/fitting/SimpleFitGui.py
Somehow an intermediate slot is needed
> [SimpleFitGui] Correct loading of functions file.

- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/math/fitting/SimpleFitGui.py
- Remember last selected counters
- Sort scanned motors in same order as appear in scan title
> [GUI] HDF5 improvements

- PyMca5/PyMcaGui/pymca/PyMcaMain.py
> Detect OpenGL risk of freezing the application

- PyMca5/PyMcaGui/io/SpecFileDataInfo.py
- PyMca5/PyMcaIO/BlissSpecFile.py
- Sort redis counters on IO
- Sort motor and counter list in SPEC-like information widget
closes #754
> [GUI] Provide some convenient sorting

- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaPostBatch.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
Respecting the user locking can originate file locks.
> Unconditionally set locking to FALSE

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
Implement the functionality available for SPEC that simplifies multiple selections.
> [HDF5] Allow to sort scans by title

- PyMca5/PyMcaGui/physics/xrf/AttenuatorsTable.py
- PyMca5/PyMcaGui/physics/xrf/FitParam.py
- PyMca5/PyMcaGui/physics/xrf/MaterialEditor.py
- PyMca5/PyMcaGui/physics/xrf/TransmissionTableEditor.py
- PyMca5/PyMcaGui/physics/xrf/TransmissionTableGui.py
- PyMca5/PyMcaIO/ArraySave.py
- PyMca5/PyMcaIO/ConfigDict.py
- PyMca5/PyMcaIO/HDF5Stack1D.py
- PyMca5/PyMcaPhysics/xrf/ClassMcaTheory.py
- PyMca5/PyMcaPhysics/xrf/ConcentrationsTool.py
- PyMca5/PyMcaPhysics/xrf/Elements.py
- PyMca5/PyMcaPhysics/xrf/FisxHelper.py
- PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
- PyMca5/tests/TestAll.py
> [XRF] Support user transmission tables as attenuators

- PyMca5/PyMcaGui/math/SGWindow.py
The sign of the derivatives of odd order was not correct if the x values were decreasing.
> [SGWindow] Deal with the case the x values are decreasing.

- PyMca5/PyMcaIO/specfile/include/locale_management.h
- PyMca5/PyMcaIO/specfile/src/locale_management.c
- PyMca5/PyMcaIO/specfile/src/sfdata.c
- PyMca5/PyMcaIO/specfile/src/sflabel.c
- PyMca5/PyMcaIO/specfile/src/sfmca.c
- PyMca5/tests/SpecfileTest.py
- setup.py
https://github.com/silx-kit/silx/pull/3316
> [I/O] Take care of compatibility with user locale under windows.

- PyMca5/PyMcaCore/StackROIBatch.py
> [ROI Batch] Make sure to work with floats.

- setup.py
> Get rid of files generated during the OpenGL headers test.

- PyMca5/PyMcaIO/specfilewrapper.py
Minimalist support to account for the measurement live time.
> Read live time from KETEK AXAS-D

- PyMca5/PyMcaPlugins/RegularMeshPlugin.py
> Make sure not to get a 2d array for the motor positions.

- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaMath/mva/NNMAModule.py
- PyMca5/PyMcaPlugins/NNMAStackPlugin.py
> [MVA] Deal with non-finite data when calculating NNMA

- PyMca5/PyMcaGui/pymca/QSource.py
> Correct shared memory issues under Python 3.8

- PyMca5/PyMcaMath/mva/PCATools.py
> [PCA] Use correct index when dealing with NaNs in stacks of spectra.

- PyMca5/PyMcaCore/XiaEdf.py
- PyMca5/PyMcaGui/pymca/XiaCorrectWizard.py
> [XiaCorrect] Adapt to python 3

- PyMca5/PyMcaGui/plotting/MaskScatterWidget.py
> [MaskScatterView] Deal with NaNs in the data.

- PyMca5/PyMcaGui/io/hdf5/HDF5Info.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
> [HDF5Widget] Handle empty fixed length datasets.

- .travis.yml
Save several minutes of testing under travis.
> [CI]Take fisx from wheelhouse to reduce power9 testing time.

- PyMca5/PyMcaGui/io/hdf5/HDF5Selection.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaIO/HDF5Stack1D.py
> [HDF5] XRF batch fitting use the selected entries when dealing with one HDF5 file

- doc/source/tutorials.rst
> Re-generate the videos in mp4 format.

- PyMca5/PyMcaIO/specfilewrapper.py
> [IO] AXAS - Calculate live time instead of reading it.

- .travis.yml
- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- PyMca5/__init__.py
- changelog.txt
Visualization of Fast XRF Fit results was not working.
> Compatibility with matplotlib 3.5.0

- PyMca5/PyMcaCore/LoggingLevel.py
It was set to INFO instead of DEFAULT_LOGGING_LEVEL
> Correct default logging level

- .github/workflows/ci.yml
- PyMca5/PyMcaGui/misc/DoubleSlider.py
- PyMca5/PyMcaGui/physics/xrf/EnergyTable.py
> [GUI] Correct PyQt5 Python3.10 issue

- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
> [ROI Tool] Add MCA on double click

- PyMca5/PyMcaGui/math/fitting/SpecfitGui.py
> [FIT] Correct recently introduced layout bug

- PyMca5/PyMcaGui/PluginsToolButton.py
- PyMca5/PyMcaGui/io/QEdfFileWidget.py
- PyMca5/PyMcaGui/io/QSourceSelector.py
- PyMca5/PyMcaGui/io/SpecFileMcaTable.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/plotting/LegendSelector.py
- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
- PyMca5/PyMcaGui/plotting/MaskScatterWidget.py
- PyMca5/PyMcaGui/plotting/MaskToolBar.py
- PyMca5/PyMcaGui/plotting/PlotWindow.py
- PyMca5/PyMcaGui/plotting/Q4PyMcaPrintPreview.py
- PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py
- PyMca5/PyMcaGui/pymca/ExternalImagesWindow.py
- PyMca5/PyMcaGui/pymca/McaCalibrationControlGUI.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaNexusWidget.py
- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave1D.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaGui/pymca/RGBCorrelator.py
- PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
- PyMca5/PyMcaGui/pymca/ScanFitToolButton.py
- PyMca5/PyMcaGui/pymca/ScanWindow.py
- PyMca5/PyMcaGui/pymca/SilxGLWindow.py
- PyMca5/PyMcaGui/pymca/SilxMcaWindow.py
- PyMca5/PyMcaGui/pymca/StackPluginResultsWindow.py
Should close #843 alike issues.
> [GUI] Get rid of .exec_ calls

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
Putting a condition on the time of the file could lead to reach a recursion limit.
> [GUI] HDF5Widget reaching recursion limit

- PyMca5/PyMcaGui/physics/xrf/PeakIdentifier.py
> [GUI] Use intermediate method to receive signal.

- package/pyinstaller/pyinstaller.spec
Generate dmg. pkg and .app on MacOS
> [Packaging] Generate .pkg installer

- package/pyinstaller/pyinstaller.spec
Try to perform the command for the user inside a postinstall script of a .pkg
> [MacOS] Add postinstall script

- PyMca5/PyMcaGui/physics/xrf/ElementsInfo.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
- PyMca5/PyMcaGui/pymca/LegacyPyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaMdi.py
> [GUI] Get rid of Qt 3 raiseW method

- PyMca5/PyMcaPlugins/NormalizationPlugins.py
Convenience for some beamlines.
> [Plugins] Add -log(I/I0) normalization

- PyMca5/PyMcaGui/physics/xrf/FitParam.py
> Limit the maximum width of the attenuators tab

- PyMca5/PyMcaIO/specfile/include/locale_management.h
- PyMca5/PyMcaIO/specfile/src/locale_management.c
- setup.py
Cleanup locale management based on contribution from @llohse #869
> [IO] Specfile locale

- PyMca5/PyMcaGui/pymca/StackSelector.py
- PyMca5/PyMcaIO/LabSpec6TxtMap.py
Only when exported as TIFF or TXT files.
> [IO] Support LabSpec 6 Maps

- PyMca5/PyMcaGui/misc/SubprocessLogWidget.py
- package/pyinstaller/pyinstaller.spec
> Update required modules for qtconsole

- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/pymca/LegacyPyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaPostBatch.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaMath/fitting/SimpleFitAll.py
> Deal with HDF5 issues in windows frozen binaries

- PyMca5/PyMcaGui/pymca/LegacyPyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaPostBatch.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
They do not provide solution of #879
> Get rid of previous changes.

- PyMca5/PyMcaGui/physics/xrf/ConcentrationsWidget.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedTable.py
> [XRF] Use clipboard enabled table

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/io/hdf5/HDF5McaTable.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaIO/ConfigDict.py
> [HDF5] Support 1D slicing

- PyMca5/PyMcaCore/PyMcaDirs.py
- PyMca5/PyMcaGui/io/PyMcaFileDialogs.py
- PyMca5/PyMcaGui/pymca/StackSelector.py
- Remember last used filter.
- Default StackSelector to HDF5. closes #835.
> [IO] Remember last user selected filter

- PyMca5/PyMcaCore/NexusTools.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
Previous version gives troubles if two top level external links point to the same entry name but in two different files.
> [HDF5] Improved ESRF external link handling

- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- PyMca5/PyMcaIO/ArtaxFileParser.py
- PyMca5/PyMcaIO/RTXMap.py
When the selection contains a single MCA, provide the associated motor positions.
> [IO] Associate motor position to single MCAs

- PyMca5/PyMcaCore/McaStackExport.py
- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
It was only possible for individual stacks but not for the stack list.
> [ROI Tool] Export calibration of all stacks

- PyMca5/PyMcaGui/physics/xrf/ElementsInfo.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
- changelog.txt
> [GUI] McaAdvancedFit Printing

- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/io/hdf5/HDF5McaTable.py
- PyMca5/PyMcaPlugins/MedianFilterScanDeglitchPlugin.py
- package/pyinstaller/pyinstaller.spec
It seems numpy 1.23.2 depends on it. Module added as hidden import.
> [PyInstaller] Module secrets missing in package

- PyMca5/PyMcaGui/plotting/SilxRGBCorrelatorGraph.py
- PyMca5/PyMcaGui/pymca/XMCDWindow.py
> [GUI] QSize Make sure to use integers.

- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- Buggy monitor handling
- Broken links were not identified
> [PyMcaGui.io.hdf5] Correct issues introduced with v5.7.3

- PyMca5/PyMcaCore/StackBase.py
> [ROI Imaging] Correct maximum MCA calculation logic.

- PyMca5/PyMcaPlugins/MaskScatterViewPlugin.py
> [ROI Imaging] Avoid positioners reset in MaskScatterViewPlugin

- PyMca5/PyMcaIO/BrukerBCF.py
- PyMca5/PyMcaIO/LispixMap.py
- Read live time from bcf files
- closes #923
> [IO] Solve bcf and Lispix conflict

- .github/workflows/ci.yml
- pyproject.toml
- setup.py
> Add pyproject toml

- .github/workflows/ci.yml
- .travis.yml
- appveyor.yml
Explicit installation of package files instead of `--find-links dist/ --no-cache-dir --no-index`
> adapt CI to pyproject.toml

- PyMca5/PyMcaGui/pymca/QDataSource.py
An OSError reported at the mailing list that could not be reproduced locally,
> [IO]Try to avoid relying on the presence of good encoder/decoders

- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/io/PyMcaFileDialogs.py
- PyMca5/PyMcaGui/io/QEdfFileWidget.py
- PyMca5/PyMcaGui/misc/NumpyArrayTableView.py
- PyMca5/PyMcaGui/misc/NumpyArrayTableWidget.py
- PyMca5/PyMcaGui/physics/xrf/XRFMCPyMca.py
- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
- PyMca5/PyMcaGui/plotting/McaROIWidget.py
- PyMca5/PyMcaGui/plotting/PlotWindow.py
- PyMca5/PyMcaGui/plotting/RGBCorrelatorGraph.py
- PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py
- PyMca5/PyMcaGui/plotting/SilxRGBCorrelatorGraph.py
- PyMca5/PyMcaGui/pymca/Mca2Edf.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/PyMcaMdi.py
- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave.py
- PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
- PyMca5/PyMcaGui/pymca/SumRulesTool.py
- README.rst
- correct initialization of classes
> [GUI] PySide6 detected issues

- .github/workflows/ci.yml
- PyMca5/PyMcaGui/physics/xrf/MaterialEditor.py
- PyMca5/PyMcaGui/pymca/XMCDWindow.py
- PyMca5/tests/WidgetsInstantiationTest.py
> [GUI] Add fully qualified enums

- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
Consider the selected area, if any, when calculating the spectrum of the maximum at each channel.
> [ROI Imaging] Calculate max spectrum for masked areas

- PyMca5/PyMcaIO/TiffIO.py
Attempt to read but provide a warning instead of raising an error.
> [IO] Ignore information from photometric interpretation

- .travis.yml
- PyMca5/tests/ElementsTest.py
Somehow stopped working on apt related issues.
> [CI] Travis issues

- PyMca5/PyMcaGui/pymca/ScanWindow.py
- PyMca5/PyMcaMath/SimpleMath.py
The single point derivative was working but not the Savitzky-Golay n-point.
> [SimpleMath] Derivative of strictly decreasing X values

- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/misc/testutils.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- PyMca5/PyMcaGui/pymca/QStackWidget.py
- doc/man/pymca.1
- doc/man/pymcaroitool.1
> [GUI] Add compatibility with PyQt6

- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- README.rst
> [DOC] Add link to web documentation under help menu

- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/physics/xrf/FastXRFLinearFitWindow.py
- PyMca5/PyMcaPlugins/FastXRFLinearFitStackPlugin.py
> [GUI] Do not modify user selected output destination

- PyMca5/PyMcaGui/math/NNMAWindow.py
- PyMca5/PyMcaGui/math/PCAWindow.py
- PyMca5/PyMcaGui/pymca/QHDF5StackWizard.py
- PyMca5/tests/WidgetsInstantiationTest.py
> Use signals introduced by Qt 5.15

- PyMca5/PyMcaPlugins/StackShowSpectra.py
Perhaps it is not a good idea because it is very slow.
closes #955
> [ROI Imaging] Support stacks of images.

- PyMca5/PyMcaGui/physics/xrf/MaterialEditor.py
> Make sure the graph is not hidden.

- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
- PyMca5/PyMcaGui/plotting/PlotWindow.py
- changelog.txt
The typical use is to autoscale the Y axis while keeping the X axis frozen.
closes #959
> [Graphics] Plot1d reset zoom based on displayed portion of active curve

- PyMca5/PyMcaIO/ArtaxFileParser.py
See https://sourceforge.net/p/pymca/mailman/message/37778651/
> [IO] Support Bruker spx files with xml extension

- PyMca5/PyMcaGui/plotting/MaskImageWidget.py
> [GUI] Reset selection mask when not applicable.

- PyMca5/PyMcaGui/PyMcaQt.py
- PyMca5/PyMcaGui/misc/testutils.py
> [GUI] Compatibility with PyQt6 shipped with Qt 6.4.3

- PyMca5/PyMcaGui/pymca/McaWindow.py
- PyMca5/PyMcaIO/RTXMap.py
- PyMca5/PyMcaMath/mva/KMeansModule.py
- PyMca5/PyMcaMath/mva/Lanczos.py
- PyMca5/tests/specfilewrapperTest.py
See https://github.com/numpy/numpy/pull/23314
> [math] Handle numpy 1.25 deprecation warnings

- package/cxfreeze/cx_setup.py
It is able to generate a folder with executable scripts.
> [packaging] Make cx_Freeze work on darwin

- PyMca5/PyMcaGui/io/QSpecFileWidget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidgetActions.py
- PyMca5/PyMcaGui/pymca/PyMcaMain.py
- changelog.txt
Long standing issue requested now by ID24-DCM.
Also related to #33
> [GUI] Handle IO default action settings

- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
- PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py
- PyMca5/PyMcaPlugins/MultipleScanToMeshPlugin.py
- changelog.txt
> ID24 detected issues

- PyMca5/PyMcaGui/misc/CalculationThread.py
Try to prevent random crashes under MacOS.
> Default to python threads

- PyMca5/PyMcaPhysics/xrf/FisxHelper.py
- changelog.txt
It needs fisx 1.3.1 or later to profit from the threads.
> [XRF] Speed up calculations using threads

- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
Only index 1 could be selected as Axis.
> [GUI][HDF5]Correct bug on axes index selection.

- PyMca5/PyMcaGui/io/hdf5/HDF5CounterTable.py
Synchronize on signal index change
> [GUI][HDF5] Synchronize indices

- .github/workflows/ci.yml
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/math/NNMADialog.py
- PyMca5/PyMcaGui/math/PCADialog.py
- PyMca5/PyMcaGui/physics/xrf/ConcentrationsWidget.py
- PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.py
- PyMca5/PyMcaGui/pymca/LegacyPyMcaBatch.py
- PyMca5/PyMcaGui/pymca/Mca2Edf.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
- PyMca5/PyMcaGui/pymca/QStack.py
- PyMca5/PyMcaPlugins/ImageAlignmentStackPlugin.py
- PyMca5/PyMcaPlugins/NNMAStackPlugin.py
- PyMca5/PyMcaPlugins/PCAStackPlugin.py
- PyMca5/PyMcaPlugins/StackROIBatchPlugin.py
- PyMca5/PyMcaPlugins/XASStackBatchPlugin.py
- PyMca5/PyMcaPlugins/XASStackNormalizationPlugin.py
Attempt to get rid of random crashes
> [GUI] Avoid the use of QThreads (at least on MacOS) 

- PyMca5/PyMcaPhysics/xrf/FisxHelper.py
> [XRF] Make sure there are at least two threads

- PyMca5/PyMcaGui/pymca/ImageListStatsWidget.py
- PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py
- PyMca5/PyMcaMath/ImageListStats.py
- changelog.txt
Only finite values considered.
> Add mean ratio and median ratio to the list of image statistics

- .github/workflows/ci.yml
> Test Ubuntu 20.04 PyQt5 version

- PyMca5/PyMcaGui/math/NNMADialog.py
- PyMca5/PyMcaGui/math/PCADialog.py
- PyMca5/PyMcaGui/physics/xrf/ConcentrationsWidget.py
- PyMca5/__init__.py
- PyMca5/tests/McaAdvancedFitWidgetTest.py
- changelog.txt
> [XRF] Correct threading issue under MacOS 

- PyMca5/PyMcaGui/pymca/StackPluginResultsWindow.py
> Update ImageListStatsWidget calculation

- .travis.yml
- PyMca5/PyMcaGui/plotting/MaskScatterWidget.py
> Get rid of deprecated histogram2d normed keyword.

- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
> Handle matplotlib 3.7.x

- PyMca5/PyMcaPhysics/xrf/FastXRFLinearFit.py
- PyMca5/__init__.py
- PyMca5/tests/FastXRFLinearFitTest.py
- PyMca5/tests/__init__.py
- changelog.txt
> [XRF] Fast fit dynamically loaded integer data gave errors.

- PyMca5/PyMcaGraph/Plot.py
- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- appveyor.yml
> [GUI] Do not set zoom mode on initialization when using silx backend

- PyMca5/PyMcaGui/pymca/QHDF5StackWizard.py
> [GUI] Correct error on slot signature.

- PyMca5/PyMcaGui/io/SpecFileDataInfo.py
> Scan header motor information can be sorted by motor name or index

- PyMca5/PyMcaPhysics/xrf/McaAdvancedFitBatch.py
If there is an error calculating the concentrations it was not clear the configuration was restored.
> [XRF] Make sure configuration is restored

- PyMca5/PyMcaGui/physics/xrf/QtMcaAdvancedFitReport.py
- PyMca5/PyMcaGui/pymca/PyMcaBatch.py
Triggered when fitting Al with a Si detector (no escape peak)
> [PyMcaBatch] Error generating report

- PyMca5/PyMcaCore/RedisTools.py
Implements suggestion in issue #905
> Adapt to blissdata

- PyMca5/PyMcaGui/io/QSpecFileWidget.py
> [GUI] Save configuration without OpenGL installed

- PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py
- PyMca5/PyMcaGui/plotting/SilxPlotActions.py
> [GUI] Add compatibility with silx 2

- package/pyinstaller/create-dmg.sh.in
The option --openfolder is not compatible with Apple Silicon
> [packaging] bless changed on Ventura Apple Silicon

- package/pyinstaller/pyinstaller.spec
Add compatibility with PyInstaller >= 6.0.0
> [Package] Recover Pyinstaller under windows

- PyMca5/PyMcaIO/MEDFile.py
- PyMca5/PyMcaIO/NexusUtils.py
> Correct warnings about invalid escape sequences

- .github/workflows/ci.yml
- PyMca5/PyMcaCore/NexusDataSource.py
- PyMca5/PyMcaGui/io/QSourceSelector.py
- PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
- PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py
- PyMca5/PyMcaGui/pymca/QDataSource.py
- PyMca5/PyMcaGui/pymca/QDispatcher.py
- appveyor.yml
> Recover spech5 functionality

- PyMca5/PyMcaGui/pymca/PyMcaNexusWidget.py
- PyMca5/PyMcaGui/pymca/QDataSource.py
Restore compatibility with https://github.com/t20100/silx/tree/tiled
> Restore compatibility with tiled branch of silx

- PyMca5/PyMcaCore/McaStackExport.py
- PyMca5/PyMcaCore/StackBase.py
- PyMca5/PyMcaCore/StackROIBatch.py
- PyMca5/PyMcaGraph/backends/GLSupport/GLPlotFrame.py
- PyMca5/PyMcaGraph/backends/GLSupport/GLSupport.py
- PyMca5/PyMcaGraph/backends/MatplotlibBackend.py
- PyMca5/PyMcaGraph/backends/_OpenGLPlotCanvas.py
- PyMca5/PyMcaGui/misc/NumpyArrayTableModel.py
- PyMca5/PyMcaGui/physics/xas/XASNormalizationWindow.py
- PyMca5/PyMcaGui/plotting/ImageView.py
- PyMca5/PyMcaGui/plotting/MaskScatterWidget.py
- PyMca5/PyMcaGui/plotting/ScatterPlotCorrelatorWidget.py
- PyMca5/PyMcaGui/plotting/SilxMaskImageWidget.py
- PyMca5/PyMcaGui/pymca/QPyMcaMatplotlibSave1D.py
- PyMca5/PyMcaGui/pymca/ScanWindowInfoWidget.py
- PyMca5/PyMcaIO/JcampReader.py
- PyMca5/PyMcaMath/ImageListStats.py
- PyMca5/PyMcaMath/SimpleMath.py
- PyMca5/PyMcaMath/fitting/Gefit.py
- PyMca5/PyMcaMath/linalg.py
- PyMca5/PyMcaMath/mva/KMeansModule.py
- PyMca5/PyMcaPhysics/xas/XASNormalization.py
- PyMca5/PyMcaPhysics/xrf/ClassMcaTheory.py
- PyMca5/tests/StackBaseTest.py
- pyproject.toml
Attempt compatibility with numpy > 1.25 and numpy 2.x
> Adapt pyproject.toml

- src/PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
Something has changed in the files:
<HDF5 dataset "end_time": shape (), type "|S26">
versus
<HDF5 dataset "end_time": shape (), type "|O">
in the recent files.
Closes #1091
> [GUI] String datasets marked as broken links

- doc/source/install.rst
> Update documentaion for Windows stand-alone app

- src/PyMca5/PyMcaGui/misc/CalculationThread.py
- src/PyMca5/PyMcaGui/physics/xrf/ConcentrationsWidget.py
- src/PyMca5/PyMcaGui/pymca/QStack.py
There were threads and waiting calculation message dialogs outside the `CalculationThread.py` module.
> [GUI] Do not use multiple thread implementations

- src/PyMca5/PyMcaGui/pymca/ScanWindow.py
Adding coordinates to cursor in ScanWindow.
> Adding coordinates to cursor in ScanWindow.

- src/PyMca5/PyMcaIO/HDF5Stack1D.py
> [IO] Avoid loop when not using a monitor

- src/PyMca5/PyMcaCore/NexusTools.py
- src/PyMca5/PyMcaGui/io/hdf5/HDF5Widget.py
> Handle broken link
